import {ActionLink,Brand} from '@/components/ui';
import {HomeNavigation} from '@/components/home/navigation';
import {HeroMotion} from '@/components/home/hero-motion';
import {Examples} from '@/components/home/examples';
import './home.css';
const steps=[['Idea','Start with a question.','Bring your own topic or brainstorm with AI. Give the story a direction.'],['Storyboard','See the whole story.','Review narration and visuals together. Edit the details, then approve generation.'],['Video','Watch it come together.','Motion graphics, voiceover and captions, timed to explain your idea clearly.'],['Publish','Give it an audience.','Download your MP4. Review the exact account and caption before Instagram delivery.']];
const faqs=[['What can I make?','The first version focuses on English educational explainers, typically 60–90 seconds, with diagrams, text, motion graphics, narration and captions.'],['Can I change the story before making the video?','Yes. Edit the combined script and storyboard or request conversational revisions. You approve the storyboard before generation and review each finished video version.'],['Which voices are available?','The current pilot uses the Daniel testing voice. Additional voices, including Indian English options, are planned; they are not available presets yet.'],['Do I need Instagram to download a video?','No. Review and download your MP4 and caption file directly from your private workspace. Connecting Instagram is optional.'],['Can I post or schedule to Instagram?','The publishing and scheduling flows are built for eligible Instagram professional accounts. Live delivery is awaiting pilot activation and verification. Nothing is posted without your explicit confirmation.'],['Who can sign in?','This is an internal pilot for approved accounts. There is no public registration or billing. If you need access, ask your project administrator.'],['How long does generation take?','Generation is asynchronous and can take several minutes. You can return to the saved project to check progress. Pilot cloud generation is enabled in controlled testing windows.']];
export default function Home(){return <div className="home"><HomeNavigation/><main id="main"><section className="home-hero home-wrap"><div className="home-hero-copy"><p className="eyebrow">A small idea. A clearer world.</p><h1>Your idea.<br/><span className="accent">Ready to play.</span></h1><p className="home-lede">Turn what you know into something people can see. Create thoughtful explainers with motion, narration and captions—all in one flow.</p><div className="home-actions"><ActionLink href="/projects">Create a video <span aria-hidden="true">↗</span></ActionLink><ActionLink href="#examples" variant="secondary">Watch an example <span aria-hidden="true">↓</span></ActionLink></div><p className="home-access">Internal pilot · Approved accounts only</p></div><HeroMotion/></section>
<section className="home-section home-wrap" id="how-it-works"><div className="home-section-heading"><p className="eyebrow">A clear path from thought to screen</p><h2>Four steps.<br/>One story worth sharing.</h2><p>You bring the idea. Stay in control of how it comes to life.</p></div><ol className="home-steps">{steps.map(([name,title,description],i)=><li key={name}><span className="home-step-number">0{i+1}</span><p className="home-meta">{name.toUpperCase()}</p><h3>{title}</h3><p>{description}</p></li>)}</ol></section>
<section className="home-section home-wrap" id="examples"><div className="home-section-heading"><p className="eyebrow">Small concepts. Clear pictures.</p><h2>Make the “aha” visible.</h2><p>Explore three short, silent motion studies. These authored demonstrations illustrate visual ideas; your workspace adds AI narration and longer stories.</p></div><Examples/></section>
<section className="home-section home-wrap home-feature-grid" aria-label="Creative controls"><div><p className="eyebrow">Everything tells the same story</p><h2>Words, motion,<br/>and a little timing.</h2><p className="home-lede">Explain a process, compare two ideas or break down a tricky concept. Visuals and captions follow the narration, so your audience can follow the thought.</p><div className="home-sync" aria-hidden="true"><span>VOICE</span><i/><span>MOTION</span><i/><span>CAPTIONS</span></div></div><div className="home-feature-notes"><article><span>01</span><div><h3>See it before you render.</h3><p>Script and storyboard live together. Review what each scene says and shows.</p></div></article><article><span>02</span><div><h3>Make a change in your words.</h3><p>Ask for a clearer explanation, edit a scene, or revise captions while keeping earlier versions.</p></div></article><article><span>03</span><div><h3>Your approval matters.</h3><p>Generation, final review and publication each have a clear confirmation. No surprise posts.</p></div></article></div></section>
<section className="home-section home-wrap"><div className="home-section-heading"><p className="eyebrow">A finished video. Your next move.</p><h2>Keep it. Share it.<br/>Choose the moment.</h2></div><div className="home-delivery">{[['↓','Download your MP4','Take the video and captions with you. No social account required.'],['↗','Connect your Instagram','A personal connection to your eligible professional account.'],['◷','Post now or schedule','Review the exact video, caption, destination and time. Live delivery is pending pilot activation.']].map(([icon,title,text])=><article key={title}><span aria-hidden="true">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="home-section home-wrap home-faq" id="faq"><div><p className="eyebrow">Before you press play</p><h2>A few good<br/>questions.</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
<section className="home-closing home-wrap"><p className="eyebrow">There’s a story in what you know</p><h2>Let’s give it<br/><span className="accent">a little motion.</span></h2><ActionLink href="/projects">Create a video <span aria-hidden="true">↗</span></ActionLink><p className="home-access">Sign in with your approved internal account.</p></section></main><footer className="home-footer home-wrap"><Brand/><p>One idea. One clear story.</p><a href="#main">Back to top ↑</a></footer></div>}
