import assert from 'node:assert/strict';
import {test} from 'node:test';
import {generationStore,createGenerationController} from '../components/storyboard/generation-controller';
const project='prj_'+'1'.repeat(32),story='stb_'+'2'.repeat(32),id='job_'+'3'.repeat(32);
const input={storyboardId:story,approvalId:'apr_'+'4'.repeat(32),expectedDraftRevision:2,expectedDraftHash:'a'.repeat(64),expectedContentHash:'b'.repeat(64),confirm:true as const};
const job={id,projectId:project,storyboardId:story,state:'queued',stage:'queued',revision:1,attempt:0,errorCode:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),finishedAt:null,actions:{cancel:true}};
function memory(){const map=new Map<string,string>();return {getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v);},removeItem:(k:string)=>{map.delete(k);}};}
test('reload recovers exact command only on explicit action; duplicate clicks suppressed',async()=>{const mem=memory(),store=generationStore(mem,'owner',project);let posts=0;const keys:string[]=[];const call=async(_url:string,init?:RequestInit)=>{if(init){posts++;keys.push((init.headers as Record<string,string>)['Idempotency-Key']);if(posts===1)throw Error('lost');return {data:job};}return {data:job};};const first=createGenerationController(project,store,call,()=>{});await first.create(input);assert.ok(first.snapshot().pending);first.dispose();const second=createGenerationController(project,store,call,()=>{});await second.load();assert.equal(posts,1);await Promise.all([second.recover(),second.recover()]);assert.equal(posts,2);assert.equal(keys[0],keys[1]);assert.equal(second.snapshot().pending,null);});
test('storage failure prevents mutation dispatch',async()=>{let calls=0;const store=generationStore({getItem:()=>null,setItem:()=>{throw Error();},removeItem:()=>{}},'owner',project);const c=createGenerationController(project,store,async()=>{calls++;return {data:job};},()=>{});await c.create(input);assert.equal(calls,0);assert.equal(c.snapshot().error,'RECOVERY_STORAGE');});
test('foreign response remains unconfirmed and pending',async()=>{const store=generationStore(memory(),'owner',project),c=createGenerationController(project,store,async()=>({data:{...job,projectId:'prj_'+'9'.repeat(32)}}),()=>{});await c.create(input);assert.ok(c.snapshot().pending);});
test('disposed response does not erase recovery state',async()=>{const store=generationStore(memory(),'owner',project);let finish!:(x:unknown)=>void;const c=createGenerationController(project,store,()=>new Promise(r=>finish=r),()=>{});const pending=c.create(input);c.dispose();finish({data:job});await pending;assert.ok(store.read());});
test('cancel stores exact revision and original key; definite conflict clears pending',async()=>{const store=generationStore(memory(),'owner',project);let body:any;const c=createGenerationController(project,store,async(_url,init)=>{if(init){body=JSON.parse(init.body as string);throw {status:409,code:'REVISION_CONFLICT'};}return {data:job};},()=>{});await c.load();await c.cancel();assert.deepEqual(body,{expectedRevision:1});assert.equal(c.snapshot().pending,null);assert.equal(c.snapshot().error,'REVISION_CONFLICT');});
test('identity/project storage is isolated',()=>{const mem=memory(),a=generationStore(mem,'a',project),b=generationStore(mem,'b',project);a.write({action:'create',key:crypto.randomUUID(),body:input});assert.equal(b.read(),null);});
