import {test} from 'node:test';
import assert from 'node:assert/strict';
import {instagramController} from '../components/instagram/controller';
const view={id:'igc_fixture',revision:2,state:'connected' as const,account:{id:'123',username:'fixture',type:'CREATOR' as const},destinationEpoch:1,expiresAt:null,publishingAvailable:false,pendingIntentCount:0};
function store():Storage{const m=new Map<string,string>();return {get length(){return m.size;},key:i=>[...m.keys()][i]??null,getItem:k=>m.get(k)??null,setItem:(k,v)=>{m.set(k,v);},removeItem:k=>{m.delete(k);},clear:()=>m.clear()};}
const base={get:async()=>({connection:view,configured:true}),connect:async()=>({authorizationUrl:'https://www.instagram.com/oauth/authorize?state=fixture'}),disconnect:async()=>({connection:{...view,revision:3,state:'disconnected' as const,account:null}})};
test('lost disconnect survives reload and replays exact key/body; reads cannot settle it',async()=>{
 const storage=store();let sent:unknown;const c=instagramController(storage,'one',{...base,disconnect:async p=>{sent=p;throw Error();}},()=>{});await c.load();await c.disconnect();assert.ok(c.snapshot().pending);c.dispose();
 const d=instagramController(storage,'one',{...base,disconnect:async p=>{assert.deepEqual(p,sent);return base.disconnect();}},()=>{});await d.load();assert.ok(d.snapshot().pending);assert.equal(await d.connect(),null);await d.recover();assert.equal(d.snapshot().pending,null);assert.equal(storage.length,0);
});
test('conflict clears rejection and requires reload before any new action',async()=>{const c=instagramController(store(),'one',{...base,disconnect:async()=>{throw {code:'REVISION_CONFLICT'};}},()=>{});await c.load();await c.disconnect();assert.equal(c.snapshot().pending,null);assert.equal(c.snapshot().ready,false);assert.equal(await c.connect(),null);await c.load();assert.equal(c.snapshot().ready,true);});
test('storage errors block disconnect; separate tab stores and owners do not clear one another',async()=>{
 const s=store();s.setItem=()=>{throw Error();};let calls=0;const c=instagramController(s,'one',{...base,disconnect:async()=>{calls++;return base.disconnect();}},()=>{});await c.load();await c.disconnect();assert.equal(calls,0);assert.equal(c.snapshot().error,'RECOVERY_STORAGE');
 const shared=store(),a=instagramController(shared,'a',{...base,disconnect:async()=>{throw Error();}},()=>{}),b=instagramController(shared,'b',base,()=>{});await a.load();await a.disconnect();await b.load();await b.disconnect();assert.equal(shared.length,1);
});
test('unconfigured status disables authorization, unexpected redirect hosts are rejected',async()=>{const c=instagramController(store(),'a',{...base,get:async()=>({connection:view,configured:false})},()=>{});await c.load();assert.equal(await c.connect(),null);const d=instagramController(store(),'b',{...base,connect:async()=>({authorizationUrl:'https://evil.example'})},()=>{});await d.load();assert.equal(await d.connect(),null);assert.equal(d.snapshot().error,'OUTCOME_UNKNOWN');});
test('disposed response and malformed success preserve recovery receipt',async()=>{const s=store();let release!:(value:Awaited<ReturnType<typeof base.disconnect>>)=>void;const c=instagramController(s,'a',{...base,disconnect:()=>new Promise(r=>release=r)},()=>{});await c.load();const pending=c.disconnect();c.dispose();release(await base.disconnect());await pending;assert.equal(s.length,1);const d=instagramController(s,'a',{...base,disconnect:async()=>({connection:null as never})},()=>{});await d.load();await d.recover();assert.ok(d.snapshot().pending);assert.equal(s.length,1);});
