import {setupJobs,assertJobsReady} from '../src/jobs/setup';
import {generationService,runGenerationJob} from '../src/jobs/service';
import {dispatchJobs} from '../src/jobs/dispatch';
import {handleJobs} from '../src/jobs/http';
import {approveStoryboard} from '../src/storyboards/approval-service';
import {storyboardService} from '../src/storyboards/service';
import {draftService} from '../src/drafts/service';
import assert from 'node:assert/strict';
import {test,before,after} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import {MongoClient} from 'mongodb';
import {MongoMemoryReplSet} from 'mongodb-memory-server';
import {setupDatabase} from '../src/db/setup';
import {setupProjects} from '../src/projects/setup';
import {setupDrafts} from '../src/drafts/setup';
import {setupIdeas} from '../src/ideas/setup';
import {setupStoryboards} from '../src/storyboards/setup';
import {setupStoryboardQueue} from '../src/storyboards/queue-setup';
import {setupEditableDrafts} from '../src/drafts/edit-setup';
import {setupStoryboardRevisions} from '../src/storyboards/revision-setup';
import {setupStoryboardSnapshots} from '../src/storyboards/snapshot-setup';
import {setupStoryboardApprovals} from '../src/storyboards/approval-setup';
import {setupStorage} from '../src/storage/setup';
import {setupAuth} from '../src/auth/setup';
import {createAuth} from '../src/auth/engine';
import {provisionUser} from '../src/auth/operator';
import {projectService} from '../src/projects/service';
let replica:MongoMemoryReplSet,client:MongoClient,db:ReturnType<MongoClient['db']>,deps:Awaited<ReturnType<typeof import('../src/auth/runtime').dependencies>>;
let owner:string,other:string,cookie:string,otherCookie:string;
const config={origin:'http://127.0.0.1:3002',secure:false,secret:randomBytes(48).toString('base64url')};
before(async()=>{
 replica=await MongoMemoryReplSet.create({binary:{version:'8.0.17'},replSet:{count:1,ip:'127.0.0.1',storageEngine:'wiredTiger'}});client=await new MongoClient(replica.getUri(),{promoteLongs:false}).connect();db=client.db('storage_test');
 for(const setup of [setupDatabase,setupProjects,setupDrafts,setupIdeas,setupStoryboards,setupStoryboardQueue,setupEditableDrafts,setupStoryboardRevisions,setupStoryboardSnapshots,setupStoryboardApprovals,setupStorage,setupJobs])await setup(db);
 await setupAuth(db,client,config);const auth=createAuth(db,client,config);deps={db,client,auth,config};const users=[];
 for(const email of ['owner@example.test','other@example.test']){const input={name:'Media QA',email,password:'Media-fixture-only-4829!'};const user=await provisionUser(db,client,config,input);const r=await auth.api.signInEmail({body:input,asResponse:true});users.push({id:user.userId,cookie:r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ')});}
 [owner,other]=users.map(u=>u.id);[cookie,otherCookie]=users.map(u=>u.cookie);
},{timeout:180000});
after(async()=>{await client?.close();await replica?.stop();});
const sentence='Water moves through our world in a repeating cycle. The sun warms the surface and turns some liquid into invisible vapor. As this vapor rises and cools it condenses into tiny droplets. These droplets gather in clouds before returning to the ground as rain and collecting in rivers and lakes.';
function fixture(){return {schemaVersion:2,title:'The water cycle',audience:'School students',learningObjective:'Understand the journey of water.',language:'en',voicePreset:'daniel-test',sources:[],scenes:Array.from({length:3},(_,i)=>({id:`scene-${i}`,title:'A journey',kicker:'WATER',narration:sentence,pronunciation:[],visual:{component:i===2?'takeaway':'title',version:1,data:{labels:['Water']}},events:[{id:'reveal',targetId:'label-1',action:'reveal',cue:{phrase:'Water',occurrence:1,offsetMs:0},durationMs:400}],sourceIds:[]}))};}

async function seed(){const project=(await projectService(db,client,config.secret).create(owner,randomUUID(),{title:'Generation fixture'})).data!;const drafts=draftService(db,client);await drafts.save(owner,project.id,{expectedRevision:1,changes:{topic:'Water cycle'}});const svc=storyboardService(db,client,config.secret,()=>({model:'fixture',run:async()=>({content:fixture()})}));await svc.create(owner,project.id,randomUUID(),{expectedDraftRevision:2});const source=(await svc.list(owner,project.id,{limit:20})).data[0];const draft=await drafts.get(owner,project.id);const approval=(await approveStoryboard(db,client,owner,project.id,randomUUID(),{storyboardId:source.id,expectedDraftRevision:draft.revision,expectedDraftHash:draft.contentHash,expectedContentHash:source.contentHash,approve:true})).data;return {project,input:{storyboardId:source.id,approvalId:approval.id,expectedDraftRevision:draft.revision,expectedDraftHash:draft.contentHash,expectedContentHash:source.contentHash,confirm:true as const}};}
const service=()=>generationService(db,client);
const fail=(p:Promise<unknown>,code:string)=>assert.rejects(p,e=>(e as {code?:string}).code===code);
const request=(action:'create'|'latest'|'read'|'cancel',id:string,body?:unknown,headers:Record<string,string>={})=>handleJobs(new Request(config.origin+'/api/test',{method:body?'POST':'GET',headers:{Cookie:cookie,Origin:config.origin,'Content-Type':'application/json','Idempotency-Key':randomUUID(),...headers},...(body?{body:JSON.stringify(body)}:{})}),action,id,async()=>deps);
test('strict migration and readiness',async()=>{await setupJobs(db);await assertJobsReady(db);await assert.rejects(db.collection('generationJobs').insertOne({untrusted:1}));await fail(assertJobsReady(client.db('none')),'JOBS_SETUP_REQUIRED');});
test('admission freezes input, commands replay and one active project slot',async()=>{const s=await seed(),key=randomUUID();const [a,b]=await Promise.all([service().create(owner,s.project.id,key,s.input),service().create(owner,s.project.id,key,s.input)]);assert.equal(a.data.id,b.data.id);assert.equal(await db.collection('generationJobs').countDocuments({projectId:s.project.id}),1);assert.equal(await db.collection('generationOutbox').countDocuments({jobId:a.data.id}),1);await fail(service().create(owner,s.project.id,randomUUID(),s.input),'PROJECT_BUSY');await fail(service().create(owner,s.project.id,key,{...s.input,expectedDraftRevision:3}),'IDEMPOTENCY_KEY_REUSED');const row=await db.collection('generationJobs').findOne({_id:a.data.id as never});assert.deepEqual(row!.inputSnapshot.plan,fixture());});
test('HTTP owner/auth/origin/schema boundaries',async()=>{const s=await seed();assert.equal((await request('create',s.project.id,s.input,{Cookie:''})).status,401);assert.equal((await request('create',s.project.id,s.input,{Cookie:otherCookie})).status,404);assert.equal((await request('create',s.project.id,s.input,{Origin:'https://other.test'})).status,403);assert.equal((await request('create',s.project.id,{...s.input,confirm:false})).status,422);const r=await request('create',s.project.id,s.input);assert.equal(r.status,202);const id=(await r.json()).data.id;assert.equal((await request('read',id,undefined,{Cookie:otherCookie})).status,404);assert.equal((await request('read',id)).headers.get('cache-control'),'private, no-store');});
test('stale content and missing approval reject without creating job',async()=>{const s=await seed();await fail(service().create(owner,s.project.id,randomUUID(),{...s.input,approvalId:'apr_'+'0'.repeat(32)}),'APPROVAL_REQUIRED');await fail(service().create(owner,s.project.id,randomUUID(),{...s.input,expectedDraftHash:'0'.repeat(64)}),'HASH_MISMATCH');await draftService(db,client).save(owner,s.project.id,{expectedRevision:2,changes:{topic:'Changed'}});await fail(service().create(owner,s.project.id,randomUUID(),s.input),'REVISION_CONFLICT');assert.equal(await db.collection('generationJobs').countDocuments({projectId:s.project.id}),0);});
test('queued cancellation replays and releases only its own slot',async()=>{const s=await seed(),j=(await service().create(owner,s.project.id,randomUUID(),s.input)).data,key=randomUUID();const result=await service().cancel(owner,j.id,key,{expectedRevision:1});assert.equal(result.data.state,'cancelled');assert.equal((await service().cancel(owner,j.id,key,{expectedRevision:1})).replayed,true);assert.equal(await runGenerationJob(db,client,j.id),false);const next=await service().create(owner,s.project.id,randomUUID(),s.input);await runGenerationJob(db,client,j.id);assert.equal((await db.collection('projects').findOne({_id:s.project.id as never}))!.activeJobId,next.data.id);});
test('cancel while running prevents completion and duplicate delivery does not claim live lease',async()=>{const s=await seed(),j=(await service().create(owner,s.project.id,randomUUID(),s.input)).data;let release!:()=>void,entered!:()=>void;const started=new Promise<void>(r=>entered=r),wait=new Promise<void>(r=>release=r);const work=runGenerationJob(db,client,j.id,undefined,async()=>{entered();await wait;});await started;assert.equal(await runGenerationJob(db,client,j.id),false);const running=await service().get(owner,j.id);assert.equal(running.state,'running');await service().cancel(owner,j.id,randomUUID(),{expectedRevision:running.revision});release();await work;assert.equal((await service().get(owner,j.id)).state,'cancelled');});
test('preflight stops honestly with renderer dependency and no output/provider call',async()=>{const s=await seed(),j=(await service().create(owner,s.project.id,randomUUID(),s.input)).data;await runGenerationJob(db,client,j.id);const done=await service().get(owner,j.id);assert.equal(done.state,'needs_input');assert.equal(done.errorCode,'RENDERER_NOT_CONNECTED');assert.equal((await db.collection('projects').findOne({_id:s.project.id as never}))!.activeJobId,undefined);assert.equal(await db.collection('assets').countDocuments({projectId:s.project.id}),0);});
test('deadline expiration is fenced and distinguishes queued expiration',async()=>{const s=await seed();let date=new Date();const svc=generationService(db,client,()=>date),j=(await svc.create(owner,s.project.id,randomUUID(),s.input)).data;date=new Date(date.getTime()+16*60000);assert.equal((await svc.get(owner,j.id)).errorCode,'QUEUE_EXPIRED');assert.equal(await runGenerationJob(db,client,j.id,()=>date),false);});
test('lease takeover fences late workers',async()=>{const s=await seed(),j=(await service().create(owner,s.project.id,randomUUID(),s.input)).data;let release!:()=>void,entered!:()=>void;let date=new Date();const started=new Promise<void>(r=>entered=r),wait=new Promise<void>(r=>release=r);const first=runGenerationJob(db,client,j.id,()=>date,async()=>{entered();await wait;});await started;date=new Date(date.getTime()+91000);await runGenerationJob(db,client,j.id,()=>date);const second=await service().get(owner,j.id);assert.equal(second.attempt,2);release();await first;assert.equal((await service().get(owner,j.id)).revision,second.revision);});
test('outbox send failure remains recoverable and payload excludes content',async()=>{const s=await seed(),j=(await service().create(owner,s.project.id,randomUUID(),s.input)).data;await db.collection('generationOutbox').updateMany({jobId:{$ne:j.id}},{$set:{state:'sent',availableAt:new Date(Date.now()+3600000)}});let date=new Date();await dispatchJobs(db,client,async()=>{throw Error('network');},()=>date);assert.equal((await db.collection('generationOutbox').findOne({jobId:j.id}))!.state,'pending');date=new Date(date.getTime()+16000);const events:any[]=[];await dispatchJobs(db,client,async e=>{events.push(e);},()=>date);assert.equal(events.length,1);assert.deepEqual(events[0].data,{jobId:j.id});await runGenerationJob(db,client,events[0].data.jobId);assert.equal((await service().get(owner,j.id)).state,'needs_input');});
test('disabled owner fails admission at worker and frees slot',async()=>{const s=await seed(),j=(await service().create(owner,s.project.id,randomUUID(),s.input)).data;await db.collection('internalAccess').updateOne({provisionedUserId:owner},{$set:{enabled:false}});try{assert.equal((await request('read',j.id)).status,403);await runGenerationJob(db,client,j.id);assert.equal((await service().get(owner,j.id)).errorCode,'ACCESS_UNAVAILABLE');}finally{await db.collection('internalAccess').updateOne({provisionedUserId:owner},{$set:{enabled:true}});}});
test('job admission transaction rolls back slot and job when outbox insertion fails',async()=>{const s=await seed();const original=(await db.listCollections({name:'generationOutbox'},{nameOnly:false}).toArray())[0].options!.validator;await db.command({collMod:'generationOutbox',validator:{$and:[original,{jobId:{$exists:false}}]}});try{await assert.rejects(service().create(owner,s.project.id,randomUUID(),s.input));}finally{await db.command({collMod:'generationOutbox',validator:original});}assert.equal(await db.collection('generationJobs').countDocuments({projectId:s.project.id}),0);assert.equal((await db.collection('projects').findOne({_id:s.project.id as never}))!.activeJobId,undefined);});
test('deleted parent and corrupted frozen input cannot progress',async()=>{const a=await seed(),b=await seed(),ja=(await service().create(owner,a.project.id,randomUUID(),a.input)).data,jb=(await service().create(owner,b.project.id,randomUUID(),b.input)).data;await db.collection('projects').updateOne({_id:a.project.id as never},{$set:{deletedAt:new Date()}});await fail(service().get(owner,ja.id),'NOT_FOUND');await runGenerationJob(db,client,ja.id);assert.equal((await db.collection('generationJobs').findOne({_id:ja.id as never}))!.errorCode,'ACCESS_UNAVAILABLE');await db.collection('generationJobs').updateOne({_id:jb.id as never},{$set:{inputHash:'0'.repeat(64)}});await runGenerationJob(db,client,jb.id);assert.equal((await service().get(owner,jb.id)).errorCode,'INPUT_INVALID');});
test('signed Inngest route fails closed without configuration or signature',async()=>{const {NextRequest}=await import('next/server');const route=await import('../app/api/inngest/route');const saved=process.env.INNGEST_SIGNING_KEY,dev=process.env.INNGEST_DEV;try{delete process.env.INNGEST_DEV;delete process.env.INNGEST_SIGNING_KEY;assert.equal((await route.POST(new NextRequest('https://app.example.test/api/inngest',{method:'POST',body:'{}'}),{})).status,503);process.env.INNGEST_SIGNING_KEY='signkey-test-'+'0'.repeat(64);const response=await route.POST(new NextRequest('https://app.example.test/api/inngest',{method:'POST',body:'{}',headers:{'Content-Type':'application/json'}}),{});assert.ok([400,401,403].includes(response.status));}finally{if(saved===undefined)delete process.env.INNGEST_SIGNING_KEY;else process.env.INNGEST_SIGNING_KEY=saved;if(dev===undefined)delete process.env.INNGEST_DEV;else process.env.INNGEST_DEV=dev;}});
