import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {publicationStore,recoverPublication,sendPublication,type Receipt} from '../components/publishing/commands';
const storage=()=>{const values=new Map<string,string>();return {getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);},removeItem:(k:string)=>{values.delete(k);}};};
const command=():Receipt=>({action:'create',key:randomUUID(),body:{projectId:'prj_'+'a'.repeat(32),payload:{videoId:'vid_'+'b'.repeat(32),videoApprovalId:'apr_'+'c'.repeat(32),expectedOutputHash:'d'.repeat(64),destination:{connectionId:'igc_'+'e'.repeat(32),instagramUserId:'123',destinationEpoch:1},caption:'Reviewed caption'},mode:'now',confirm:true}});
const view=(c:ReturnType<typeof command>)=>{if(c.action!=='create')throw Error();return {id:'pub_'+'f'.repeat(32),projectId:c.body.projectId,revision:1,state:'queued',videoId:c.body.payload.videoId,videoTitle:'Fixture',assetHash:c.body.payload.expectedOutputHash,destination:{...c.body.payload.destination,usernameAtApproval:'fixture'},caption:c.body.payload.caption,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),publishedAt:null,providerMediaId:null,permalink:null,errorCode:null,mode:'now',schedule:null,retryDeadlineAt:null,actions:{cancel:true,retry:false,edit:true}} as const;};
test('lost response retains exact command for reload recovery; successful replay clears only matching receipt',async()=>{const s=publicationStore(storage(),'owner','project'),c=command();s.write(c);await assert.rejects(recoverPublication(s,c,async()=>{throw Error('lost');}));assert.deepEqual(s.read(),c);const newer=command();await recoverPublication(s,c,async()=>{s.write(newer);return view(c);});assert.deepEqual(s.read(),newer);});
test('tab-scoped stores do not erase other tabs and owner/project scopes remain isolated',async()=>{const a=publicationStore(storage(),'owner','project'),b=publicationStore(storage(),'owner','project'),ca=command(),cb=command();a.write(ca);b.write(cb);await recoverPublication(a,ca,async()=>view(ca));assert.equal(a.read(),null);assert.deepEqual(b.read(),cb);});
test('explicit rejection clears receipt but malformed or mismatched success keeps recovery',async()=>{const s=publicationStore(storage(),'owner','project'),c=command();s.write(c);await assert.rejects(recoverPublication(s,c,async()=>{throw {definite:true,code:'DESTINATION_CHANGED'};}));assert.equal(s.read(),null);s.write(c);await assert.rejects(recoverPublication(s,c,x=>sendPublication(x,(async()=>Response.json({data:{...view(c),caption:'wrong'}})) as typeof fetch)));assert.deepEqual(s.read(),c);});
test('same idempotency key/body is sent on recovery, and disabled publication is an explicit rejection',async()=>{const c=command();await sendPublication(c,(async(_url,init)=>{assert.equal((init?.headers as any)['Idempotency-Key'],c.key);assert.deepEqual(JSON.parse(init!.body as string),c.body);return Response.json({data:view(c)});}) as typeof fetch);await assert.rejects(sendPublication(c,(async()=>Response.json({error:{code:'PUBLISHING_DISABLED'}},{status:503})) as typeof fetch),e=>(e as any).definite===true);});
test('replacement recovery keeps exact schedule/body/key after lost response',async()=>{
 const base=command();if(base.action!=='create')throw Error();const c:Receipt={action:'replace',id:'pub_'+'f'.repeat(32),key:randomUUID(),body:{...base.body,expectedRevision:4,mode:'schedule',schedule:{localTime:'2030-01-01T18:00',timezone:'Asia/Kolkata',utcOffset:'+05:30'}}};
 const store=publicationStore(storage(),'owner','project');store.write(c);await assert.rejects(recoverPublication(store,c,async()=>{throw {definite:false};}));assert.deepEqual(store.read(),c);
 let calls=0;const result=await sendPublication(c,async(url,options)=>{calls++;assert.equal(url,`/api/publish-intents/${c.id}`);assert.equal(options?.method,'PATCH');assert.equal(JSON.parse(String(options?.body)).schedule.timezone,'Asia/Kolkata');return Response.json({data:{...view(base),revision:5,state:'scheduled',mode:'schedule',schedule:{...c.body.schedule,utc:'2030-01-01T12:30:00.000Z'}}});});assert.equal(result.state,'scheduled');assert.equal(calls,1);
});
test('old create recovery accepts current replaced payload only on authoritative idempotent replay',async()=>{
 const c=command(),changed={...view(c),caption:'Replacement confirmed elsewhere'};
 await assert.rejects(sendPublication(c,async()=>Response.json({data:changed})));
 const r=await sendPublication(c,async()=>Response.json({data:changed},{headers:{'Idempotency-Replayed':'true'}}));assert.equal(r.caption,changed.caption);
});
