import assert from 'node:assert/strict';
import {test,before,after} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import {MongoClient} from 'mongodb';
import {MongoMemoryReplSet} from 'mongodb-memory-server';
import {setupDatabase} from '../src/db/setup';
import {setupProjects} from '../src/projects/setup';
import {setupDrafts} from '../src/drafts/setup';
import {setupIdeas} from '../src/ideas/setup';
import {setupStoryboards} from '../src/storyboards/setup';
import {setupStoryboardQueue} from '../src/storyboards/queue-setup';
import {setupEditableDrafts} from '../src/drafts/edit-setup';
import {setupStoryboardRevisions} from '../src/storyboards/revision-setup';
import {setupStoryboardSnapshots} from '../src/storyboards/snapshot-setup';
import {setupStoryboardApprovals} from '../src/storyboards/approval-setup';
import {setupStorage,assertStorageReady} from '../src/storage/setup';
import {setupAuth} from '../src/auth/setup';
import {createAuth} from '../src/auth/engine';
import {provisionUser} from '../src/auth/operator';
import {projectService} from '../src/projects/service';
import {storageService,digest} from '../src/storage/service';
import {handleMedia} from '../src/storage/http';
import {gateway,byteRange,type Bucket} from '../src/storage/gateway';
import {serviceSignature,authPath} from '../src/storage/wire';
import {r2Store,type ObjectStore} from '../src/storage/r2';
import {r2Config,deliveryConfig} from '../src/storage/config';
let replica:MongoMemoryReplSet,client:MongoClient,db:ReturnType<MongoClient['db']>,deps:Awaited<ReturnType<typeof import('../src/auth/runtime').dependencies>>;
let owner:string,other:string,cookie:string,otherCookie:string;
const config={origin:'http://127.0.0.1:3002',secure:false,secret:randomBytes(48).toString('base64url')},delivery={origin:'https://media.example.test',secret:randomBytes(48).toString('base64url')};
before(async()=>{
 replica=await MongoMemoryReplSet.create({binary:{version:'8.0.17'},replSet:{count:1,ip:'127.0.0.1',storageEngine:'wiredTiger'}});client=await new MongoClient(replica.getUri(),{promoteLongs:false}).connect();db=client.db('storage_test');
 for(const setup of [setupDatabase,setupProjects,setupDrafts,setupIdeas,setupStoryboards,setupStoryboardQueue,setupEditableDrafts,setupStoryboardRevisions,setupStoryboardSnapshots,setupStoryboardApprovals,setupStorage])await setup(db);
 await setupAuth(db,client,config);const auth=createAuth(db,client,config);deps={db,client,auth,config};const users=[];
 for(const email of ['owner@example.test','other@example.test']){const input={name:'Media QA',email,password:'Media-fixture-only-4829!'};const user=await provisionUser(db,client,config,input);const r=await auth.api.signInEmail({body:input,asResponse:true});users.push({id:user.userId,cookie:r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ')});}
 [owner,other]=users.map(u=>u.id);[cookie,otherCookie]=users.map(u=>u.cookie);
},{timeout:180000});
after(async()=>{await client?.close();await replica?.stop();});
const fail=(p:Promise<unknown>,code:string)=>assert.rejects(p,e=>(e as {code:string}).code===code);
function memory(){const objects=new Map<string,{bytes:Uint8Array;type:string;hash:string}>();let puts=0;
 const store:ObjectStore={async put(key,bytes,type,hash){puts++;if(!objects.has(key))objects.set(key,{bytes:Uint8Array.from(bytes),type,hash});},async verify(key,size,hash,type){const a=objects.get(key);if(!a||a.bytes.length!==size||digest(a.bytes)!==hash||a.type!==type)throw {code:'ASSET_INTEGRITY_FAILED'};}};
 const bucket:Bucket={async head(key){const a=objects.get(key);return a?{size:a.bytes.length,customMetadata:{sha256:a.hash},httpMetadata:{contentType:a.type}}:null;},async get(key,options){const a=objects.get(key);if(!a)return null;const range=options?.range;const bytes=range?a.bytes.slice(range.offset,range.offset+range.length):a.bytes;return {...(await bucket.head(key))!,body:new ReadableStream({start(c){c.enqueue(bytes);c.close();}})};}};
 return {store,bucket,objects,puts:()=>puts};}
async function seed(kind:'video'|'thumbnail'|'timeline'='video'){
 const project=(await projectService(db,client,config.secret).create(owner,randomUUID(),{title:'Media fixture'})).data!;const input={id:`ast_${randomUUID().replaceAll('-','')}`,projectId:project.id,kind,producerFingerprint:'a'.repeat(64)};const bytes=new TextEncoder().encode('0123456789'),storage=memory(),service=storageService(db,client);await service.upload(owner,input,bytes,storage.store);return {project,input,bytes,storage,service};
}
const req=(action:'list'|'access'|'revoke',id:string,body?:unknown,headers:Record<string,string>={},query='')=>handleMedia(new Request(config.origin+'/api/test'+query,{method:action==='list'?'GET':'POST',headers:{Cookie:cookie,Origin:config.origin,'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})}),action,id,async()=>deps,()=>delivery);
async function signed(body:string,nonce=randomUUID(),time=Date.now().toString()){return new Request(config.origin+authPath,{method:'POST',headers:{'x-media-time':time,'x-media-nonce':nonce,'x-media-signature':await serviceSignature(delivery.secret,body,time,nonce)},body});}
const authCall=(async(url:RequestInfo|URL,init?:RequestInit)=>handleMedia(new Request(String(url),init),'authorize','',async()=>deps,()=>delivery)) as typeof fetch;
const env=(bucket:Bucket)=>({MEDIA_BUCKET:bucket,APP_ORIGIN:config.origin,MEDIA_SERVICE_SECRET:delivery.secret});
test('migration strictness, replay and setup readiness',async()=>{await setupStorage(db);await assertStorageReady(db);await assert.rejects(db.collection('assets').insertOne({unexpected:true}));await assert.rejects(db.collection('mediaGrants').insertOne({unexpected:true}));await fail(assertStorageReady(client.db('absent')),'STORAGE_SETUP_REQUIRED');});
test('upload validates private immutable reference; exact retries preserve one asset',async()=>{const s=await seed();await s.service.upload(owner,s.input,s.bytes,s.storage.store);assert.equal(await db.collection('assets').countDocuments({projectId:s.project.id}),1);assert.equal(s.storage.objects.size,1);const row=await db.collection('assets').findOne({_id:s.input.id as never});assert.equal(row?.state,'ready');assert.equal(row?.sha256,digest(s.bytes));await fail(s.service.upload(owner,s.input,new Uint8Array([1]),s.storage.store),'ASSET_CONFLICT');await fail(s.service.upload(other,s.input,s.bytes,s.storage.store),'NOT_FOUND');await fail(s.service.upload(owner,{...s.input,id:'ast_'+'0'.repeat(32)},new Uint8Array(0),s.storage.store),'INVALID_ASSET');});
test('unconfirmed upload remains staging and retry recovers the same object',async()=>{const s=await seed();const input={...s.input,id:'ast_'+randomUUID().replaceAll('-','')};const store={...s.storage.store,async verify(){throw {code:'ASSET_INTEGRITY_FAILED'};}};await fail(s.service.upload(owner,input,s.bytes,store),'ASSET_INTEGRITY_FAILED');assert.equal((await db.collection('assets').findOne({_id:input.id as never}))?.state,'staging');await fail(s.service.access(owner,input.id,'preview',delivery.origin),'ASSET_NOT_READY');await s.service.upload(owner,input,s.bytes,s.storage.store);assert.equal((await db.collection('assets').findOne({_id:input.id as never}))?.state,'ready');});
test('upload finalization cannot resurrect tombstoned project',async()=>{const s=await seed();const input={...s.input,id:'ast_'+randomUUID().replaceAll('-','')};await fail(s.service.upload(owner,input,s.bytes,{...s.storage.store,async verify(){await db.collection('projects').updateOne({_id:s.project.id as never},{$set:{deletedAt:new Date()}});}}),'NOT_FOUND');assert.equal((await db.collection('assets').findOne({_id:input.id as never}))?.state,'staging');});
test('owner-only list/access, origin checks, strict purposes and internal artifact privacy',async()=>{const s=await seed();assert.equal((await req('access',s.input.id,{purpose:'preview'},{Cookie:''})).status,401);assert.equal((await req('access',s.input.id,{purpose:'preview'},{Cookie:otherCookie})).status,404);assert.equal((await req('list',s.project.id,undefined,{Cookie:otherCookie})).status,404);assert.equal((await req('access',s.input.id,{purpose:'preview'},{Origin:'https://bad.test'})).status,403);assert.equal((await req('access',s.input.id,{purpose:'ingest'})).status,422);const r=await req('list',s.project.id);const body=await r.json();assert.equal(body.data[0].id,s.input.id);assert.equal(JSON.stringify(body).includes('objectKey'),false);assert.equal(r.headers.get('cache-control'),'private, no-store');const internal=await seed('timeline');assert.equal((await req('access',internal.input.id,{purpose:'download'})).status,404);});
test('grant is hashed, expires synchronously and revokes on subsequent requests',async()=>{const s=await seed();let date=new Date();const service=storageService(db,client,()=>date);const access=await service.access(owner,s.input.id,'preview',delivery.origin),token=access.url.split('/').at(-1)!;const record=await db.collection('mediaGrants').findOne({assetId:s.input.id});assert.equal(record?.tokenHash,digest(token));assert.equal(JSON.stringify(record).includes(token),false);await service.authorize({token,method:'GET'});date=new Date(date.getTime()+600001);await fail(service.authorize({token,method:'GET'}),'NOT_FOUND');const fresh=await s.service.access(owner,s.input.id,'download',delivery.origin);await s.service.revoke(owner,s.input.id);await fail(s.service.authorize({token:fresh.url.split('/').at(-1)!,method:'GET'}),'NOT_FOUND');});
test('disabled owners and deleted or non-ready assets invalidate issued grants',async()=>{const s=await seed();const grant=await s.service.access(owner,s.input.id,'preview',delivery.origin),body={token:grant.url.split('/').at(-1)!,method:'GET' as const};await db.collection('assets').updateOne({_id:s.input.id as never},{$set:{state:'deleting'}});await fail(s.service.authorize(body),'NOT_FOUND');await db.collection('assets').updateOne({_id:s.input.id as never},{$set:{state:'ready'}});await db.collection('internalAccess').updateOne({provisionedUserId:owner},{$set:{enabled:false}});try{await fail(s.service.authorize(body),'NOT_FOUND');}finally{await db.collection('internalAccess').updateOne({provisionedUserId:owner},{$set:{enabled:true}});}await db.collection('projects').updateOne({_id:s.project.id as never},{$set:{deletedAt:new Date()}});await fail(s.service.authorize(body),'NOT_FOUND');});
test('service HMAC rejects replays, stale timestamps and tampering before asset lookup',async()=>{const s=await seed(),grant=await s.service.access(owner,s.input.id,'preview',delivery.origin),body=JSON.stringify({token:grant.url.split('/').at(-1),method:'GET'}),nonce=randomUUID();const request=await signed(body,nonce);assert.equal((await handleMedia(request.clone(),'authorize','',async()=>deps,()=>delivery)).status,200);assert.equal((await handleMedia(request,'authorize','',async()=>deps,()=>delivery)).status,404);assert.equal((await handleMedia(await signed(body,randomUUID(),String(Date.now()-31000)),'authorize','',async()=>deps,()=>delivery)).status,404);const valid=await signed(body);const bad=new Request(valid.url,{method:'POST',headers:valid.headers,body:body+' '});assert.equal((await handleMedia(bad,'authorize','',async()=>deps,()=>delivery)).status,404);});
test('gateway full, HEAD, bounded/open/suffix ranges and malformed 416',async()=>{const s=await seed(),grant=await s.service.access(owner,s.input.id,'preview',delivery.origin);for(const [range,expected] of [['bytes=2-4','234'],['bytes=7-','789'],['bytes=-3','789'],['bytes=8-99','89']] as const){const r=await gateway(new Request(grant.url,{headers:{Range:range}}),env(s.storage.bucket),authCall);assert.equal(r.status,206);assert.equal(await r.text(),expected);assert.equal(r.headers.get('accept-ranges'),'bytes');}const full=await gateway(new Request(grant.url),env(s.storage.bucket),authCall);assert.equal(full.status,200);assert.equal(await full.text(),'0123456789');const head=await gateway(new Request(grant.url,{method:'HEAD'}),env(s.storage.bucket),authCall);assert.equal(head.headers.get('content-length'),'10');assert.equal(await head.text(),'');for(const range of ['bytes=99-','bytes=1-0','bytes=0-1,4-5','bytes=-0']){const r=await gateway(new Request(grant.url,{headers:{Range:range}}),env(s.storage.bucket),authCall);assert.equal(r.status,416);assert.equal(r.headers.get('content-range'),'bytes */10');}});
test('gateway denies revoked/missing/corrupt media and wrong browser origins without caching or leaking keys',async()=>{const s=await seed(),grant=await s.service.access(owner,s.input.id,'download',delivery.origin);const good=await gateway(new Request(grant.url,{headers:{Origin:config.origin}}),env(s.storage.bucket),authCall);assert.match(good.headers.get('content-disposition')!,/^attachment/);assert.equal(good.headers.get('access-control-allow-origin'),config.origin);assert.equal(good.headers.get('cache-control'),'private, no-store');assert.equal((await gateway(new Request(grant.url,{headers:{Origin:'https://bad.test'}}),env(s.storage.bucket),authCall)).status,403);const obj=[...s.storage.objects.values()][0];obj.hash='0'.repeat(64);assert.equal((await gateway(new Request(grant.url),env(s.storage.bucket),authCall)).status,503);s.storage.objects.clear();assert.equal((await gateway(new Request(grant.url),env(s.storage.bucket),authCall)).status,404);await s.service.revoke(owner,s.input.id);let reads=0;assert.equal((await gateway(new Request(grant.url),env({head:async()=>{reads++;return null;},get:async()=>{reads++;return null;}}),authCall)).status,404);assert.equal(reads,0);});
test('asset-bearing empty projects cannot be deleted by the scaffold cleanup path',async()=>{const s=await seed();await fail(projectService(db,client,config.secret).remove(owner,s.project.id,randomUUID(),{expectedRevision:1,confirm:true}),'PROJECT_DELETE_UNAVAILABLE');});
test('pagination remains owner/project scoped with bounded strict cursor queries',async()=>{const s=await seed();await s.service.upload(owner,{...s.input,id:'ast_'+randomUUID().replaceAll('-','')},s.bytes,s.storage.store);const first=await (await req('list',s.project.id,undefined,{},'?limit=1')).json();assert.equal(first.data.length,1);assert.equal(first.page.hasMore,true);const next=await (await req('list',s.project.id,undefined,{},`?limit=1&cursor=${first.page.nextCursor}`)).json();assert.notEqual(next.data[0].id,first.data[0].id);assert.equal(next.page.hasMore,false);assert.equal((await req('list',s.project.id,undefined,{},'?limit=100')).status,422);});
test('R2 adapter binds immutable put and verifies bytes by streaming SHA256, never ETag',async()=>{const body=new TextEncoder().encode('media'),hash=digest(body);const commands:any[]=[];const fake={send:async(cmd:any)=>{commands.push(cmd.input);if(commands.length===1)return {};return {Metadata:{sha256:hash},ContentLength:body.length,ContentType:'video/mp4',Body:(async function*(){yield body;})()};}};const r2=r2Store({bucket:'test',endpoint:'https://test',accessKeyId:'test',secretAccessKey:'test'},fake as never);await r2.put('key',body,'video/mp4',hash);await r2.verify('key',body.length,hash,'video/mp4');assert.equal(commands[0].IfNoneMatch,'*');assert.equal(commands[0].Metadata.sha256,hash);await fail(r2.verify('key',body.length,'0'.repeat(64),'video/mp4'),'ASSET_INTEGRITY_FAILED');});
test('configuration rejects arbitrary endpoints and invalid origins; range parser rejects unsafe integers',()=>{assert.throws(()=>r2Config({}));assert.throws(()=>deliveryConfig({MEDIA_GATEWAY_ORIGIN:'https://media.test/path',MEDIA_SERVICE_SECRET:'x'.repeat(32)}));assert.throws(()=>byteRange('bytes=999999999999999999999-',10));});
test('verified object survives DB-finalization failure as staging and is recoverable',async()=>{const s=await seed(),input={...s.input,id:'ast_'+randomUUID().replaceAll('-','')};const definition=(await db.listCollections({name:'assets'},{nameOnly:false}).toArray())[0].options!.validator;await db.command({collMod:'assets',validator:{$and:[definition,{$or:[{_id:{$ne:input.id}},{state:{$ne:'ready'}}]}]}});try{await assert.rejects(s.service.upload(owner,input,s.bytes,s.storage.store));}finally{await db.command({collMod:'assets',validator:definition});}assert.equal((await db.collection('assets').findOne({_id:input.id as never}))?.state,'staging');await s.service.upload(owner,input,s.bytes,s.storage.store);assert.equal((await db.collection('assets').findOne({_id:input.id as never}))?.state,'ready');});
test('concurrent identical upload retries never produce a second asset or changed bytes',async()=>{const s=await seed();const input={...s.input,id:'ast_'+randomUUID().replaceAll('-','')};await Promise.all([s.service.upload(owner,input,s.bytes,s.storage.store),s.service.upload(owner,input,s.bytes,s.storage.store)]);assert.equal(await db.collection('assets').countDocuments({_id:input.id as never}),1);const row=await db.collection('assets').findOne({_id:input.id as never});assert.equal(row?.sha256,digest(s.bytes));assert.equal(row?.state,'ready');});
test('gateway auth outage fails closed; mismatched If-Range returns full content',async()=>{const s=await seed(),grant=await s.service.access(owner,s.input.id,'preview',delivery.origin);let reads=0;const bucket={head:async()=>{reads++;return null;},get:async()=>{reads++;return null;}};assert.equal((await gateway(new Request(grant.url),env(bucket),(async()=>new Response(null,{status:503})) as typeof fetch)).status,503);assert.equal(reads,0);const response=await gateway(new Request(grant.url,{headers:{Range:'bytes=2-4','If-Range':'"old"'}}),env(s.storage.bucket),authCall);assert.equal(response.status,200);assert.equal(await response.text(),'0123456789');});

test('R2 verification rejects intact bytes with missing gateway checksum metadata',async()=>{const body=new TextEncoder().encode('media');const fake={send:async()=>({ContentLength:body.length,ContentType:'video/mp4',Body:(async function*(){yield body;})()})};const store=r2Store({bucket:'test',endpoint:'https://test',accessKeyId:'test',secretAccessKey:'test'},fake as never);await fail(store.verify('key',body.length,digest(body),'video/mp4'),'ASSET_INTEGRITY_FAILED');});
