'use client';
import {useEffect,useRef,useState} from 'react';
import {Brand,Button} from '../ui';
import {SignOutButton} from '../private-session';
import {instagramController,instagramTransport,initialInstagramState} from './controller';
import {signInLocation} from '../../src/auth/navigation';
const outcomes:Record<string,string>={connected:'Instagram connected. Review your account below.',not_configured:'Direct Instagram connection is being set up. Please try again once it is available.',page_required:'The previous Facebook connection flow is no longer available. Use Connect Instagram to authorize directly.',page_unavailable:'The previous Facebook connection could not be completed. Use Connect Instagram to authorize directly.',cancelled:'Authorization was cancelled. Your previous connection is unchanged.',permissions:'Instagram profile and publishing permissions are both required. Connect again and allow both permissions.',professional_required:'Choose an Instagram Creator or Business account. If you have a personal account, switch to a professional account in Instagram first. You can still download your videos.',account_unavailable:'This Instagram account cannot be connected to this workspace. Choose another account.',expired:'This authorization expired, was already used, or was replaced. Start a new connection.',provider_error:'Instagram could not confirm authorization. Reload the connection to check the result before trying again.',sign_in_required:'Your session expired. Start Connect Instagram again after signing in.',pending_publication:'Resolve pending publication before changing this connection.'};
export function InstagramConnection({userId,name,outcome,project}:{userId:string;name:string;outcome?:string;project?:string}){
 const [state,setState]=useState(initialInstagramState),[confirm,setConfirm]=useState(false);const controller=useRef<ReturnType<typeof instagramController>|null>(null);
 useEffect(()=>{let c:ReturnType<typeof instagramController>;try{c=instagramController(sessionStorage,userId,instagramTransport,s=>{setState(s);if(s.error==='UNAUTHENTICATED')window.location.replace(signInLocation('expired'));if(s.error==='ACCESS_DISABLED')window.location.replace('/access-help?state=disabled');});controller.current=c;void c.load();}catch{setState({...initialInstagramState,error:'RECOVERY_STORAGE'});return;}return()=>c.dispose();},[userId]);
 const connection=state.connection,blocked=state.busy||!!state.pending||!state.ready;
 const error=state.error==='INSTAGRAM_NOT_CONFIGURED'?outcomes.not_configured:state.error==='VALIDATION_FAILED'?'Could not start this connection. Reload and try again.':state.error==='REVISION_CONFLICT'?'This connection changed in another tab. Reload and review the current account before disconnecting.':state.error==='CONNECTION_RECONCILIATION_PENDING'?'Resolve pending publication before changing this connection.':state.error==='RECOVERY_STORAGE'?'Browser recovery storage is unavailable. Enable storage and reload before changing your connection.':state.error?'Could not confirm the request. Recover a pending disconnect or reload the connection.':'';
 return <div className="library-shell library-base"><aside className="library-sidebar"><Brand/><p className="workspace-label">PERSONAL WORKSPACE</p><nav aria-label="Workspace"><a href="/projects">My videos</a><a href="/settings">Settings</a><a href="/settings/instagram" aria-current="page">Instagram</a></nav></aside><div className="library-content"><header className="library-topbar"><a href="/settings">← Settings</a><div className="library-account"><span>{name}</span><SignOutButton/></div></header><main id="main" className="preferences-main"><p className="eyebrow">YOUR NEXT CONNECTION</p><h1>From your workspace<br/>to your audience.</h1><p className="muted">Connect directly with Instagram. A Creator or Business account is required; no Facebook Page is needed.</p>
 {outcome&&outcomes[outcome]&&<p className="notice" role="status">{outcomes[outcome]}</p>}{error&&<p role="alert">{error}</p>}{state.busy&&<p role="status">Checking your connection…</p>}
 <section className="panel preferences-form"><h2>Instagram</h2>{state.ready&&!state.configured&&<p className="notice">Direct Instagram connection is being set up. Please try connecting again once setup is complete. You can still download your videos.</p>}
 {connection?.account?<><p className="instagram-identity">@{connection.account.username}</p><p>{connection.account.type==='CREATOR'?'Creator':connection.account.type==='BUSINESS'?'Business':'Professional'} account · {connection.state.replaceAll('_',' ')}</p>{connection.provider==='facebook'&&<p className="muted">This account uses the previous Facebook connection. Reconnect to authorize directly with Instagram. Reconnecting won’t replace the saved account until Instagram confirms the new one.</p>}{connection.expiresAt&&<p className="muted">Authorization expires {new Date(connection.expiresAt).toLocaleDateString('en-IN')}.</p>}</>:<p>No Instagram account connected.</p>}
 <p>You’ll continue to Instagram’s official authorization page to sign in if needed and allow profile and publishing access. Review the account shown before authorizing. NamasteVideo never asks for your Instagram password.</p><p className="muted">Connecting does not publish a video. You choose and confirm each video before posting or scheduling it. Video downloads remain available.</p>
 {state.pending?<div className="notice"><h3>Confirm your disconnect</h3><p>The last response was not confirmed. Recover the original request before changing this connection.</p><Button disabled={state.busy} onClick={()=>void controller.current?.recover()}>Recover disconnect</Button></div>:<div className="actions"><Button disabled={blocked||!state.configured} onClick={()=>void controller.current?.connect(project).then(url=>{if(url)window.location.assign(url);})}>{connection?.account?'Reconnect Instagram':'Connect Instagram'}</Button>{connection?.account&&<Button variant="secondary" disabled={blocked} onClick={()=>setConfirm(true)}>Disconnect</Button>}</div>}
 {confirm&&!state.pending&&<section className="notice" role="group" aria-label="Confirm disconnect"><h3>Disconnect @{connection?.account?.username}?</h3><p>This removes this workspace’s saved authorization. It does not delete Instagram posts. Unsubmitted requests will pause. Already submitted requests may still publish; we retain only their encrypted recovery credentials to check the outcome.</p><div className="actions"><Button disabled={blocked} onClick={()=>{setConfirm(false);void controller.current?.disconnect();}}>Confirm disconnect</Button><Button variant="secondary" onClick={()=>setConfirm(false)}>Keep connected</Button></div></section>}
 <Button variant="secondary" disabled={state.busy} onClick={()=>{setConfirm(false);void controller.current?.load();}}>Reload connection</Button></section>{project&&<p><a href={`/projects/${project}/video`}>← Return to your video</a></p>}
 </main></div></div>;
}
