'use client';
import {useEffect,useRef,useState} from 'react';
import {Brand,Button} from '../ui';
import {SignOutButton} from '../private-session';
import {instagramController,instagramTransport,initialInstagramState} from './controller';
import {facebookPageId} from '../../src/instagram/contracts';
import {signInLocation} from '../../src/auth/navigation';
const outcomes:Record<string,string>={connected:'Instagram connected. Review your account below.',page_required:'Enter the Facebook Page ID linked to your Instagram account, then connect again.',page_unavailable:'The selected Facebook Page is unavailable or has no accessible Instagram Creator or Business account. Check the Page ID and authorize access to that Page.',cancelled:'Authorization was cancelled. Your previous connection is unchanged.',permissions:'Profile and publishing permissions are both required. Try connecting again.',professional_required:'Choose an Instagram Creator or Business account. Personal accounts are not supported; you can still download your videos.',account_unavailable:'This Instagram account cannot be connected to this workspace. Choose another account.',expired:'This authorization expired, was already used, or was replaced. Start a new connection.',provider_error:'Instagram could not confirm authorization. Reload the connection to check the result before trying again.',sign_in_required:'Your session expired. Start Connect Instagram again after signing in.',pending_publication:'Resolve pending publication before changing this connection.'};
export function InstagramConnection({userId,name,outcome,project}:{userId:string;name:string;outcome?:string;project?:string}){
 const [state,setState]=useState(initialInstagramState),[confirm,setConfirm]=useState(false),[pageId,setPageId]=useState<string|null>(null);const controller=useRef<ReturnType<typeof instagramController>|null>(null);
 useEffect(()=>{let c:ReturnType<typeof instagramController>;try{c=instagramController(sessionStorage,userId,instagramTransport,s=>{setState(s);if(s.error==='UNAUTHENTICATED')window.location.replace(signInLocation('expired'));if(s.error==='ACCESS_DISABLED')window.location.replace('/access-help?state=disabled');});controller.current=c;void c.load();}catch{setState({...initialInstagramState,error:'RECOVERY_STORAGE'});return;}return()=>c.dispose();},[userId]);
 const connection=state.connection,facebook=state.provider==='facebook',selectedPageId=pageId??connection?.page?.id??'',validPageId=facebookPageId.safeParse(selectedPageId).success,blocked=state.busy||!!state.pending||!state.ready;
 const error=state.error==='PAGE_REQUIRED'?'Enter the numeric Facebook Page ID linked to your Instagram account.':state.error==='VALIDATION_FAILED'?'Check your connection details and try again.':state.error==='REVISION_CONFLICT'?'This connection changed in another tab. Reload and review the current account before disconnecting.':state.error==='CONNECTION_RECONCILIATION_PENDING'?'Resolve pending publication before changing this connection.':state.error==='RECOVERY_STORAGE'?'Browser recovery storage is unavailable. Enable storage and reload before changing your connection.':state.error?'Could not confirm the request. Recover a pending disconnect or reload the connection.':'';
 return <div className="library-shell library-base"><aside className="library-sidebar"><Brand/><p className="workspace-label">PERSONAL WORKSPACE</p><nav aria-label="Workspace"><a href="/projects">My videos</a><a href="/settings">Settings</a><a href="/settings/instagram" aria-current="page">Instagram</a></nav></aside><div className="library-content"><header className="library-topbar"><a href="/settings">← Settings</a><div className="library-account"><span>{name}</span><SignOutButton/></div></header><main id="main" className="preferences-main"><p className="eyebrow">YOUR NEXT CONNECTION</p><h1>From your workspace<br/>to your audience.</h1><p className="muted">Connect your own Instagram Creator or Business account.</p>
 {outcome&&outcomes[outcome]&&<p className="notice" role="status">{outcomes[outcome]}</p>}{error&&<p role="alert">{error}</p>}{state.busy&&<p role="status">Checking your connection…</p>}
 <section className="panel preferences-form"><h2>Instagram</h2>{state.ready&&!state.configured&&<p className="notice">Instagram setup is pending. Your workspace administrator needs to configure the official connection before you can connect.</p>}
 {connection?.account?<><p className="instagram-identity">@{connection.account.username}</p><p>{connection.account.type==='CREATOR'?'Creator':connection.account.type==='BUSINESS'?'Business':'Professional'} account · {connection.state.replaceAll('_',' ')}</p>{connection.page&&<p className="muted">Linked Facebook Page: {connection.page.name} · {connection.page.id}</p>}{connection.expiresAt?<p className="muted">Authorization expires {new Date(connection.expiresAt).toLocaleDateString('en-IN')}.</p>:connection.provider==='facebook'&&<p className="muted">Meta reported no scheduled expiration for this authorization. Access can still be revoked; reconnect if it becomes unavailable.</p>}</>:<p>No Instagram account connected.</p>}
 {facebook&&<><label htmlFor="facebook-page-id">Linked Facebook Page ID<input id="facebook-page-id" name="pageId" inputMode="numeric" autoComplete="off" maxLength={100} value={selectedPageId} disabled={blocked} aria-describedby="facebook-page-help" aria-invalid={selectedPageId.length>0&&!validPageId} onChange={e=>setPageId(e.target.value)}/></label><p id="facebook-page-help" className="muted">Enter the numeric ID of the Facebook Page linked to your Instagram Creator or Business account. You can find it in your Facebook Page’s About or Page transparency information. Select this same Page and Instagram account during authorization.</p>{selectedPageId.length>0&&!validPageId&&<p role="alert">Use only digits for the Facebook Page ID.</p>}</>}<p>You’ll continue to {facebook?'Facebook':'Instagram'}’s official authorization page. NamasteVideo never asks for your {facebook?'Facebook or Instagram':'Instagram'} password.</p>{facebook&&<p className="muted">Authorize only your selected Page and Instagram account. We request profile, Page access and Instagram publishing permissions; business portfolio management access is not requested.</p>}<p className="muted">Connecting does not publish a video. Posting and scheduling are coming in the next milestones. Video downloads remain available.</p>
 {state.pending?<div className="notice"><h3>Confirm your disconnect</h3><p>The last response was not confirmed. Recover the original request before changing this connection.</p><Button disabled={state.busy} onClick={()=>void controller.current?.recover()}>Recover disconnect</Button></div>:<div className="actions"><Button disabled={blocked||!state.configured||(facebook&&!validPageId)} onClick={()=>void controller.current?.connect(project,facebook?selectedPageId:undefined).then(url=>{if(url)window.location.assign(url);})}>{connection?.account?'Reconnect Instagram':'Connect Instagram'}</Button>{connection?.account&&<Button variant="secondary" disabled={blocked} onClick={()=>setConfirm(true)}>Disconnect</Button>}</div>}
 {confirm&&!state.pending&&<section className="notice" role="group" aria-label="Confirm disconnect"><h3>Disconnect @{connection?.account?.username}?</h3><p>This removes this workspace’s saved authorization. It does not delete Instagram posts. Any pending publication must be resolved first.</p><div className="actions"><Button disabled={blocked} onClick={()=>{setConfirm(false);void controller.current?.disconnect();}}>Confirm disconnect</Button><Button variant="secondary" onClick={()=>setConfirm(false)}>Keep connected</Button></div></section>}
 <Button variant="secondary" disabled={state.busy} onClick={()=>{setConfirm(false);void controller.current?.load();}}>Reload connection</Button></section>{project&&<p><a href={`/projects/${project}/video`}>← Return to your video</a></p>}
 </main></div></div>;
}
