'use client';
import {useEffect,useRef,useState} from 'react';
export function HeroMotion(){
 const host=useRef<HTMLDivElement>(null),time=useRef(0),[elapsed,setElapsed]=useState(8),[paused,setPaused]=useState(false),[visible,setVisible]=useState(false),[reduced,setReduced]=useState(true),[foreground,setForeground]=useState(true);
 useEffect(()=>{const visibility=()=>setForeground(!document.hidden);visibility();document.addEventListener('visibilitychange',visibility);const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);time.current=media.matches?8:0;setElapsed(time.current);};update();media.addEventListener('change',update);const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.25});if(host.current)observer.observe(host.current);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',visibility);media.removeEventListener('change',update);};},[]);
 useEffect(()=>{if(reduced||paused||!visible||!foreground||time.current>=8)return;let raf=0,previous=0;const tick=(now:number)=>{if(document.hidden){previous=0;raf=requestAnimationFrame(tick);return;}if(previous)time.current=Math.min(8,time.current+(now-previous)/1000);previous=now;setElapsed(time.current);if(time.current<8)raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[paused,visible,reduced,foreground]);
 const step=elapsed<1.5?0:elapsed<3?1:elapsed<6?2:3;
 return <div ref={host} className="home-stage" aria-label="Silent illustration of an idea becoming a video"><div className="home-stage-top"><span>FROM A QUESTION TO A STORY</span><span>0{step+1} / 04</span></div><div className="home-idea"><span>THE IDEA</span><p>“Explain binary search. Make it click.”</p></div><div className="home-frames" aria-hidden="true">{['Find the middle','Narrow the search','Make it clear'].map((text,i)=><span className={step>=1?'is-revealed':''} key={text}><i>0{i+1}</i>{text}</span>)}</div><div className="home-demo-frame"><span className="home-demo-label">BINARY SEARCH</span><h2>Less searching.<br/><em>More finding.</em></h2><div className="home-number-row" aria-hidden="true">{[2,5,8,11,13,14,21].map((n,i)=><span key={n} className={`${step===2&&i===3||step===3&&i===5?'is-found':''} ${step===3&&i<4?'is-discarded':''}`}>{n}</span>)}</div><p>{['Start with a sorted list.','Plan the story, scene by scene.','Check the middle. Halve the search.','There it is. 14, found in two checks.'][step]}</p><div className="home-playhead" aria-hidden="true"><i style={{transform:`scaleX(${elapsed/8})`}}/></div></div><div className="home-motion-controls"><span>8-second motion illustration · silent</span>{!reduced&&<button type="button" onClick={()=>{if(time.current>=8){time.current=0;setElapsed(0);setPaused(true);requestAnimationFrame(()=>setPaused(false));}else setPaused(v=>!v);}}>{elapsed>=8?'Replay':paused?'Resume':'Pause'} animation</button>}{reduced&&<span>Reduced motion</span>}</div></div>;
}
