import {z} from 'zod';
import {connectInput,disconnectInput,connectionView} from './contracts';
export function instagramPaths(){
 const content=(schema:unknown)=>({'application/json':{schema}}),body=(s:z.ZodType)=>({required:true,content:content(z.toJSONSchema(s))}),result=(schema:unknown)=>({description:'Owner-scoped response. Authorization alone does not submit media; publishing has a separate rollout gate.',content:content({type:'object',required:['data','meta'],properties:{data:schema,meta:{type:'object'}}})}),errors=Object.fromEntries([401,403,404,409,413,415,422,503].map(status=>[status,{$ref:'#/components/responses/Error'}]));
 const origin={in:'header',name:'Origin',required:true,schema:{type:'string'}},connection=z.toJSONSchema(connectionView);
 const maintenance={post:{
  operationId:'refreshInstagramToken',
  description:'Disabled unless INSTAGRAM_REFRESH_ENABLED=1. Requires a distinct server-only bearer, empty body and no query. Renews at most one eligible admitted direct account; never publishes or renders.',
  parameters:[{in:'header',name:'Authorization',required:true,schema:{type:'string',pattern:'^Bearer .+'}}],
  responses:{
   200:{description:'Bounded maintenance result; no tokens/account IDs.',content:content({type:'object',required:['data'],properties:{data:{type:'object',required:['result'],properties:{result:{enum:['skipped','refreshed','retry_later','reconnect_required','superseded']}}}}})},
   400:{description:'Method/query/body not supported.'},401:{description:'Maintenance bearer missing or invalid.'},503:{description:'Disabled or unavailable.'},
  },
 }};
 const deauthorize={post:{operationId:'deauthorizeInstagram',security:[],description:'Meta server callback. Disabled unless INSTAGRAM_LIFECYCLE_ENABLED=1 and migration 020 is ready. Requires HMAC-SHA256 signed_request from the configured Instagram app. App-scoped subject mapping is captured during OAuth. No session/cookie/origin required. Revokes saved credentials; pauses unsent work, leaves submitted outcomes for manual review. Does not delete local projects or Instagram posts.',requestBody:{required:true,content:{'application/x-www-form-urlencoded':{schema:{type:'object',additionalProperties:false,required:['signed_request'],properties:{signed_request:{type:'string',maxLength:16384}}}}}},responses:{200:{description:'Callback applied or replay acknowledged; no account details.',content:content({type:'object',properties:{success:{const:true}}})},400:{description:'Invalid signature/payload/query or body timeout.'},413:{description:'Body exceeds 20KB.'},415:{description:'Expected form encoding.'},503:{description:'Disabled, configuration/migration missing, or transaction failed. Retry delivery.'}}}};
 const deletion={post:{...deauthorize.post,operationId:'requestInstagramDataDeletion',description:'Signed Meta deletion callback. Requires lifecycle and deletion flags plus migrations 020/021. Same subject and issued_at replay returns the same opaque confirmation code. Verified mapped data is removed transactionally; unknown publication outcomes, newer consent or ambiguous identity/history remain under operator review. Generated videos, login accounts, Instagram posts and minimal replay/duplicate safety records are retained. No auth cookies required.',responses:{...deauthorize.post.responses,200:{description:'Durable receipt; this response does not mean deletion completed. Open the status URL.',content:content({type:'object',required:['url','confirmation_code'],properties:{url:{type:'string',format:'uri'},confirmation_code:{type:'string',pattern:'^[a-f0-9]{64}$'}}})}}}};
 return {'/api/instagram/data-deletion':deletion,'/api/instagram/deauthorize':deauthorize,'/api/internal/instagram-refresh':maintenance,'/api/instagram/connect':{post:{operationId:'connectInstagram',parameters:[origin],requestBody:body(connectInput),description:'Creates a ten-minute, single-use session-bound authorization. New connects supersede earlier callbacks. Only a configured HTTPS same-origin callback is accepted. Uses direct Instagram Login only: no Facebook Page or Page ID is accepted. Instagram provider and app are pinned to the receipt. Legacy Facebook configuration cannot start new authorizations.',responses:{...errors,200:result({type:'object',required:['authorizationUrl','expiresAt'],properties:{authorizationUrl:{type:'string',format:'uri'},expiresAt:{type:'string',format:'date-time'}}})}}},'/api/instagram/callback':{get:{operationId:'instagramCallback',parameters:['state','code','error'].map(name=>({in:'query',name,required:name==='state',schema:{type:'string'}})),responses:{303:{description:'Relative settings redirect with allowlisted outcome only. Requires the initiating session; missing sessions must restart. No provider text, codes or tokens are returned.',headers:{Location:{schema:{type:'string'}}}}}}},'/api/instagram/connection':{get:{operationId:'getInstagramConnection',responses:{...errors,200:{...result({anyOf:[connection,{type:'null'}]}),headers:{'X-Instagram-Provider':{description:'New connections use direct Instagram Login. A saved legacy connection may still report its original provider in data.',schema:{const:'instagram'}},'X-Instagram-Configured':{description:'Direct Instagram Login configuration readiness only, not live provider verification; false for legacy Facebook configuration.',schema:{enum:['true','false']}}}}}},delete:{operationId:'disconnectInstagram',parameters:[origin,{in:'header',name:'Idempotency-Key',required:true,schema:{type:'string',minLength:16,maxLength:128}}],requestBody:body(disconnectInput),description:'CAS disconnect and durable same-key replay. Removes active connection credentials and pauses unsubmitted requests. Retains encrypted credentials needed to reconcile already-submitted outcomes. Does not revoke other applications or delete posts.',responses:{...errors,200:result({type:'object',required:['connection','pausedIntentCount','reconciliationPending'],properties:{connection,pausedIntentCount:{type:'integer',minimum:0},reconciliationPending:{type:'boolean'}}})}}}};
}
