'use client';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {assetView,accessView} from '../../src/storage/contracts';
import {Button} from '../ui';
import {signInLocation} from '../../src/auth/navigation';
type Asset=z.infer<typeof assetView>;type Grant=z.infer<typeof accessView>;
export function MediaLibrary({projectId}:{projectId:string}){
 const [assets,setAssets]=useState<Asset[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
 const [selected,setSelected]=useState<{asset:Asset;grant:Grant;purpose:'preview'|'download'}|null>(null),[expired,setExpired]=useState(false),[mediaError,setMediaError]=useState(false);
 const lock=useRef(false),active=useRef(true),player=useRef<HTMLMediaElement|null>(null),seek=useRef(0);
 async function call(url:string,body?:unknown){const r=await fetch(url,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000),...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw {code:result.error?.code??'STORAGE_UNAVAILABLE'};return result;}
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();}catch(e){if(active.current){const code=(e as {code?:string}).code;if(code==='UNAUTHENTICATED')window.location.replace(signInLocation('expired'));else if(code==='ACCESS_DISABLED')window.location.replace('/access-help?state=disabled');setError(code==='NOT_FOUND'?'This project or asset is unavailable.':code==='ASSET_NOT_READY'?'This asset is still being prepared.':code==='STORAGE_NOT_CONFIGURED'?'Private storage needs administrator configuration.':'Media could not be loaded. Retry when your connection is available.');}}finally{lock.current=false;if(active.current)setBusy(false);}}
 async function load(more=false){await run(async()=>{const result=await call(`/api/projects/${projectId}/assets?limit=20${more&&cursor?`&cursor=${cursor}`:''}`);const rows=z.array(assetView).parse(result.data);if(active.current){setAssets(old=>more?[...new Map([...old,...rows].map(a=>[a.id,a])).values()]:rows);setCursor(z.string().nullable().parse(result.page.nextCursor));setLoaded(true);}});}
 async function access(asset:Asset,purpose:'preview'|'download',retain=false){await run(async()=>{const grant=accessView.parse((await call(`/api/assets/${asset.id}/access`,{purpose})).data);if(active.current){seek.current=retain?(player.current?.currentTime??seek.current):0;setSelected({asset,grant,purpose});setExpired(false);setMediaError(false);}});}
 useEffect(()=>{active.current=true;void load();return()=>{active.current=false;};},[projectId]);
 useEffect(()=>{if(!selected)return;const timer=setTimeout(()=>{seek.current=player.current?.currentTime??0;setExpired(true);},Math.max(0,Date.parse(selected.grant.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[selected]);
 const canRead=(a:Asset)=>a.state==='ready'&&['video','preview','audio','thumbnail','captions'].includes(a.kind);
 return <main id="main" className="container foundation" data-private-focus-scope><a href={`/projects/${projectId}/storyboard`}>← Storyboard</a><p className="eyebrow">YOUR PROJECT FILES</p><h1>Private media.</h1><p>Generated media stays in your workspace. Preview and download links expire after ten minutes.</p><Button disabled={busy} variant="secondary" onClick={()=>void load()}>Refresh media</Button>
 {error&&<p role="alert" className="notice notice--error">{error}</p>}{!loaded?<p role="status">{busy?'Loading media…':'Refresh to load media.'}</p>:assets.length===0?<section className="panel"><h2>No media yet</h2><p>Your storyboard is saved separately. Audio and video will appear here once rendering is connected. Approval alone does not generate files.</p></section>:<ul className="media-list">{assets.map(a=><li className="panel" key={a.id}><h2>{a.kind} · {a.id.slice(-8)}</h2><p>{a.state} · {(a.bytes/1024/1024).toFixed(2)} MB</p><div className="actions"><Button disabled={busy||!canRead(a)||a.kind==='captions'} onClick={()=>void access(a,'preview')}>Preview {a.kind}</Button><Button disabled={busy||!canRead(a)} variant="secondary" onClick={()=>void access(a,'download')}>Prepare download</Button><Button disabled={busy} variant="secondary" onClick={()=>void run(async()=>{await call(`/api/assets/${a.id}/revoke`,{});if(active.current&&selected?.asset.id===a.id){setSelected(null);setExpired(false);}})}>Revoke links</Button></div></li>)}</ul>}
 {cursor&&<Button disabled={busy} onClick={()=>void load(true)}>Load more media</Button>}
 {selected&&<section className="panel media-preview" aria-label="Selected media"><h2>{selected.asset.kind} · {selected.asset.id.slice(-8)}</h2>{expired||mediaError?<><p role="status">{expired?'This link expired.':'Media is missing, expired, or temporarily unavailable.'} Refresh access to try again; this does not regenerate media.</p><Button disabled={busy} onClick={()=>void access(selected.asset,selected.purpose,true)}>Refresh access</Button></>:selected.purpose==='download'?<a className="button button--primary" href={selected.grant.url} referrerPolicy="no-referrer">Download {selected.asset.kind}</a>:selected.asset.kind==='thumbnail'?<img src={selected.grant.url} alt="Generated thumbnail" referrerPolicy="no-referrer" onError={()=>setMediaError(true)}/>:selected.asset.kind==='audio'?<audio key={selected.grant.url} ref={element=>{player.current=element;}} controls src={selected.grant.url} onLoadedMetadata={()=>{if(player.current)player.current.currentTime=seek.current;}} onError={()=>setMediaError(true)}/>:<video key={selected.grant.url} ref={element=>{player.current=element;}} controls playsInline src={selected.grant.url} onLoadedMetadata={()=>{if(player.current)player.current.currentTime=seek.current;}} onError={()=>setMediaError(true)}/>}<p>Revoking links blocks subsequent requests. Already downloaded or buffered bytes cannot be recalled.</p></section>}
 </main>;
}
