'use client';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {Button} from '../ui';
import {videoView,type Video} from '../../src/videos/contracts';
import {connectionView,type ConnectionView} from '../../src/instagram/contracts';
import {intentView,publishInput,type PublishIntent} from '../../src/publishing/contracts';
import {scheduleChoices,resolveSchedule} from '../../src/publishing/schedule';
import {validTimezone} from '../../src/preferences/contracts';
import {publicationStore,recoverPublication,type Receipt} from './commands';
import {signInLocation} from '../../src/auth/navigation';
const historySchema=z.object({data:z.array(intentView),page:z.object({nextCursor:z.string().nullable()}),enabled:z.boolean()});
const labels:Record<string,string>={scheduled:'Scheduled',queued:'Queued for Instagram',preparing:'Preparing the Reel',processing:'Instagram is processing your video',submitting:'Submitting to Instagram',published:'Published',paused_auth:'Review your connection',failed_safe:'Not published — safe to retry',outcome_unknown:'Publication outcome unconfirmed',needs_attention:'Publication needs manual review',cancelled:'Cancelled'};
export function PublishPanel({projectId,videoId,userId}:{projectId:string;videoId:string;userId:string}){
 const [video,setVideo]=useState<Video|null>(null),[connection,setConnection]=useState<ConnectionView|null>(null),[rows,setRows]=useState<PublishIntent[]>([]),[cursor,setCursor]=useState<string|null>(null),[enabled,setEnabled]=useState(false),[caption,setCaption]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Receipt|null>(null),[confirmation,setConfirmation]=useState<Receipt|null>(null),[preview,setPreview]=useState<string|null>(null),[confirmationDetails,setConfirmationDetails]=useState<{account:string;caption:string;videoId:string;timing?:string}|null>(null);
 const [mode,setMode]=useState<'now'|'schedule'>('now'),[localTime,setLocalTime]=useState(''),[timezone,setTimezone]=useState('Asia/Kolkata'),[utcOffset,setUtcOffset]=useState(''),[editing,setEditing]=useState<PublishIntent|null>(null);
 const scheduleKey=`namaste:post-schedule:${userId}:${projectId}:${videoId}`;
 const choices=scheduleChoices(localTime,timezone),chosenOffset=utcOffset||(choices.length===1?choices[0].utcOffset:'');
 function saveTiming(next:{mode:'now'|'schedule';localTime:string;timezone:string;utcOffset:string;editing:PublishIntent|null}){try{sessionStorage.setItem(scheduleKey,JSON.stringify(next));setMode(next.mode);setLocalTime(next.localTime);setTimezone(next.timezone);setUtcOffset(next.utcOffset);setEditing(next.editing);}catch{setError('Could not save scheduling changes in this tab.');}}
 const active=useRef(false),lock=useRef(false),storage=useRef<ReturnType<typeof publicationStore>|null>(null),draftKey=`namaste:post-caption:${userId}:${projectId}:${videoId}`;
 async function get(url:string,body?:unknown){const r=await fetch(url,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000),...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const b=await r.json();if(!r.ok)throw {code:b.error?.code,message:b.error?.message};return b;}
 function failure(e:unknown){const x=e as {code?:string;message?:string};if(x.code==='UNAUTHENTICATED')window.location.replace(signInLocation('expired'));else if(x.code==='ACCESS_DISABLED')window.location.replace('/access-help?state=disabled');setError(x.code==='RETRY_WINDOW_EXPIRED'?'The delivery window expired. Edit the request and confirm a new time.':x.code==='INTENT_ALREADY_CLAIMED'?'Delivery has started. Your edits were not applied; refresh to review the outcome.':x.code==='PUBLICATION_EXISTS'?'This video already has a publication for this account. Review the history below.':x.code==='PUBLISHING_DISABLED'?'Publishing is awaiting administrator activation. Nothing was queued.':x.code==='REVISION_CONFLICT'?'Publication changed in another tab. Refresh and review its current state.':x.code==='DESTINATION_CHANGED'||x.code==='RECONNECT_REQUIRED'?'The destination changed or needs reconnecting. Refresh and review the account again.':x.code==='VIDEO_NOT_APPROVED'?'Approve this exact video in the video review screen.':x.message??'Could not confirm this request. Recover it below if pending; otherwise refresh.');}
 async function load(more=false){if(lock.current)return;lock.current=true;setBusy(true);try{const [v,c,h]=await Promise.all([get(`/api/videos/${videoId}`),get('/api/instagram/connection'),get(`/api/projects/${projectId}/publish-intents?limit=20${more&&cursor?`&cursor=${cursor}`:''}`)]);const selected=videoView.parse(v.data);if(selected.projectId!==projectId)throw {code:'NOT_FOUND',message:'Video does not belong to this project.'};const history=historySchema.parse(h);if(!active.current)return;setVideo(selected);setConnection(c.data?connectionView.parse(c.data):null);setRows(old=>more?[...new Map([...old,...history.data].map(x=>[x.id,x])).values()]:history.data);setCursor(history.page.nextCursor);setEnabled(history.enabled);setReady(true);}catch(e){if(active.current)failure(e);}finally{lock.current=false;if(active.current)setBusy(false);}}
 useEffect(()=>{active.current=true;try{storage.current=publicationStore(sessionStorage,userId,projectId);setPending(storage.current.read());setCaption(sessionStorage.getItem(draftKey)??'');const saved=sessionStorage.getItem(scheduleKey);if(saved){const t=JSON.parse(saved);if(t.mode==='now'||t.mode==='schedule'){setMode(t.mode);setLocalTime(t.localTime);setTimezone(t.timezone);setUtcOffset(t.utcOffset);setEditing(t.editing?intentView.parse(t.editing):null);}}else{const browser=Intl.DateTimeFormat().resolvedOptions().timeZone;setTimezone(validTimezone(browser)?browser:'Asia/Kolkata');void get('/api/preferences').then(p=>{if(active.current&&!sessionStorage.getItem(scheduleKey)&&validTimezone(p.data?.timezone))setTimezone(p.data.timezone);}).catch(()=>undefined);}}catch{setError('Browser recovery storage is unavailable. Enable it before publishing.');storage.current=null;}void load();return()=>{active.current=false;};},[projectId,videoId,userId]);
 useEffect(()=>{if(!rows.some(r=>['scheduled','queued','preparing','processing','submitting','outcome_unknown'].includes(r.state)))return;const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},10000);return()=>clearInterval(timer);},[rows]);
 async function submit(command:Receipt,recover=false){if(lock.current||!storage.current)return;lock.current=true;setBusy(true);setError('');try{if(!recover){storage.current.write(command);setPending(command);}setConfirmation(null);const result=await recoverPublication(storage.current,command);if(active.current){setRows(old=>[result,...old.filter(r=>r.id!==result.id)]);setPending(null);if(command.action==='replace'||command.action==='create'){setEditing(null);sessionStorage.removeItem(scheduleKey);}}}catch(e){if(active.current){try{setPending(storage.current.read());}catch{storage.current=null;}failure(e);}}finally{lock.current=false;if(active.current)setBusy(false);}}
 function review(){if(!video?.approval||!connection?.account)return;try{const schedule=mode==='schedule'?{localTime,timezone,utcOffset:chosenOffset}:undefined;if(schedule)resolveSchedule(schedule,new Date());const body=publishInput.parse({projectId,payload:{videoId:video.id,videoApprovalId:video.approval.id,expectedOutputHash:video.outputHash,destination:{connectionId:connection.id,instagramUserId:connection.account.id,destinationEpoch:connection.destinationEpoch},caption},mode,...(schedule?{schedule}:{}),confirm:true});setConfirmationDetails({account:connection.account.username,caption:body.payload.caption,videoId:video.id});setConfirmation(editing?{key:crypto.randomUUID(),action:'replace',id:editing.id,body:{...body,expectedRevision:editing.revision}}:{key:crypto.randomUUID(),action:'create',body});setError('');}catch(e){if(e instanceof z.ZodError)setError('Choose a valid date, timezone and UTC offset before continuing.');else failure(e);}}
 function edit(r:PublishIntent){try{sessionStorage.setItem(draftKey,r.caption);setCaption(r.caption);saveTiming({mode:r.mode,localTime:r.schedule?.localTime??'',timezone:r.schedule?.timezone??timezone,utcOffset:r.schedule?.utcOffset??'',editing:r});setConfirmation(null);window.scrollTo({top:0,behavior:'smooth'});}catch{setError('Could not retain these edits for recovery.');}}

 const blocked=busy||!!pending||!storage.current,existing=rows.some(r=>r.videoId===videoId&&r.destination.instagramUserId===connection?.account?.id);
 return <main id="main" tabIndex={-1} className="container foundation video-review" data-private-focus-scope><nav className="actions" aria-label="Project steps"><a href="/projects">← My videos</a><a href={`/projects/${projectId}/video`}>Video review</a><span aria-current="step">04 · Publish</span></nav><p className="eyebrow">READY FOR THE WORLD</p><h1>Your next Reel.</h1><p>Review the exact video, destination and caption before posting.</p>
 {error&&<p role="alert" className="notice notice--error">{error}</p>}
 {pending&&<section className="notice"><h2>Recover your request</h2><p>The {pending.action} response is unconfirmed. Recovery reuses the same command; it does not create a second post.</p><Button disabled={busy} onClick={()=>void submit(pending,true)}>Recover request</Button></section>}
 <Button variant="secondary" disabled={busy} onClick={()=>{setConfirmation(null);void load();}}>Refresh publication status</Button>
 {!ready?<p role="status">{busy?'Loading your publication details…':'Refresh to load your publication details.'}</p>:<div className="video-review-grid"><section className="panel"><p className="eyebrow">EXACT VIDEO</p><h2>{video?.title}</h2><p>Version {video?.id.slice(-8)} · {Math.round(video?.duration??0)} seconds</p>{!video?.approval?<p className="notice">This version needs approval. <a href={`/projects/${projectId}/video`}>Review and approve it</a> first.</p>:<p>Approved video version</p>}
 {preview&&<div className="video-review-player"><video aria-label="Publication video preview" controls playsInline src={preview} onError={()=>{setPreview(null);setError('Preview expired. Open it again; the saved video is unchanged.');}}/></div>}
 <Button variant="secondary" disabled={blocked||!video} onClick={async()=>{if(!video||lock.current)return;lock.current=true;setBusy(true);try{const b=await get(`/api/assets/${video.outputAssetId}/access`,{purpose:'preview'});if(active.current)setPreview(b.data.url);}catch(e){failure(e);}finally{lock.current=false;setBusy(false);}}}>Open video preview</Button>
 <h3>Instagram destination</h3>{connection?.account?<p><strong>@{connection.account.username}</strong> · {connection.state.replaceAll('_',' ')}</p>:<p>No Instagram account connected.</p>}<a href={`/settings/instagram?project=${projectId}`}>Manage Instagram connection</a>
 {editing&&<section className="notice"><h3>Replace publication {editing.id.slice(-8)}</h3><p>Your changes will use the approved video shown here and the currently connected account. The original stays unchanged until confirmation.</p><p>Saved video: {(rows.find(r=>r.id===editing.id)?.videoId??editing.videoId).slice(-8)}</p><p className="publish-caption-text">Saved: {rows.find(r=>r.id===editing.id)?.caption??editing.caption}</p><p>{rows.find(r=>r.id===editing.id)?.schedule?.localTime} {rows.find(r=>r.id===editing.id)?.schedule?.timezone} UTC{rows.find(r=>r.id===editing.id)?.schedule?.utcOffset} → @{rows.find(r=>r.id===editing.id)?.destination.usernameAtApproval}</p>{rows.find(r=>r.id===editing.id)&&rows.find(r=>r.id===editing.id)!.revision!==editing.revision&&<Button disabled={blocked||!!confirmation} onClick={()=>saveTiming({mode,localTime,timezone,utcOffset,editing:rows.find(r=>r.id===editing.id)!})}>Use my edits against this saved revision</Button>}<Button variant="secondary" disabled={blocked||!!confirmation} onClick={()=>saveTiming({mode,localTime,timezone,utcOffset,editing:null})}>Stop replacing</Button></section>}
 <label className="publish-caption">Post caption<textarea aria-label="Post caption" rows={6} value={caption} disabled={blocked||!!confirmation} onChange={e=>{try{sessionStorage.setItem(draftKey,e.target.value);setCaption(e.target.value);}catch{setError('Could not save your caption for recovery.');}}}/></label><p>{[...caption].length} / 2,200 characters · Saved in this tab</p>
 <fieldset className="publish-timing" disabled={blocked||!!confirmation}><legend>When to publish</legend><label><input type="radio" name="publish-mode" checked={mode==='now'} onChange={()=>saveTiming({mode:'now',localTime,timezone,utcOffset,editing})}/> Post now</label><label><input type="radio" name="publish-mode" checked={mode==='schedule'} onChange={()=>saveTiming({mode:'schedule',localTime,timezone,utcOffset,editing})}/> Schedule</label>{mode==='schedule'&&<><label>Date and local time<input aria-label="Scheduled local time" type="datetime-local" value={localTime} onInput={e=>saveTiming({mode,localTime:e.currentTarget.value,timezone,utcOffset:'',editing})}/></label><label>Timezone<input aria-label="Schedule timezone" value={timezone} placeholder="Asia/Kolkata" onChange={e=>saveTiming({mode,localTime,timezone:e.target.value,utcOffset:'',editing})}/></label>{choices.length>1?<label>This time occurs twice — choose an offset<select aria-label="UTC offset" value={chosenOffset} onChange={e=>saveTiming({mode,localTime,timezone,utcOffset:e.target.value,editing})}><option value="">Choose occurrence</option>{choices.map(c=><option key={c.utc} value={c.utcOffset}>UTC{c.utcOffset} ({c.utc})</option>)}</select></label>:localTime&&<p>{choices.length?`UTC${chosenOffset}`:'Choose a valid date, time and timezone. This time may not exist due to daylight saving.'}</p>}<p>At least five minutes ahead. Delivery starts at this time; Instagram processing can delay visibility. If more than 15 minutes late, we stop and ask you to choose again.</p></>}</fieldset>
 {!enabled&&<p className="notice">Posting is awaiting administrator activation. You can review your video and prepare a caption now.</p>}
 <Button disabled={blocked||!enabled||!video?.approval||!connection?.publishingAvailable||[...caption].length>2200||(existing&&!editing)||!!confirmation} onClick={review}>{editing?'Review replacement':mode==='schedule'?'Review schedule':'Review post'}</Button>{existing&&!editing&&<p>This version already has a publication for this account. Use its history below.</p>}
 {confirmation&&<section className="notice" aria-label="Confirm Instagram publication"><h3>{(confirmation.action==='create'||confirmation.action==='replace')?(confirmation.body.mode==='schedule'?'Confirm scheduled Reel?':'Post this Reel now?'):confirmation.action==='cancel'?'Cancel before submission?':'Retry this exact post?'}</h3>{(confirmation.action==='create'||confirmation.action==='replace')?<><p>Video {confirmationDetails?.videoId.slice(-8)} → <strong>@{confirmationDetails?.account}</strong></p><p className="publish-caption-text">{confirmation.body.payload.caption||'(No caption)'}</p>{confirmation.body.schedule&&<p><strong>{confirmation.body.schedule.localTime.replace('T',' ')} · {confirmation.body.schedule.timezone} · UTC{confirmation.body.schedule.utcOffset}</strong></p>}<p>{confirmation.body.mode==='schedule'?'At the confirmed time, this sends':'This sends'} the approved video and caption to Instagram and publishes a Reel to this account. It may appear in the feed. Publishing cannot be cancelled once submission starts.</p></>:<><p>Video {confirmationDetails?.videoId.slice(-8)} → <strong>@{confirmationDetails?.account}</strong></p><p className="publish-caption-text">{confirmationDetails?.caption||'(No caption)'}</p><p>{confirmationDetails?.timing}</p><p>{confirmation.action==='retry'?'Uses the original video, caption and original account and confirmed time. If that time has passed, delivery starts now within its remaining window. Refresh the connection first if required.':'An already submitted post cannot be cancelled here.'}</p></>}<div className="actions"><Button disabled={blocked} onClick={()=>void submit(confirmation)}>{(confirmation.action==='create'||confirmation.action==='replace')?(confirmation.body.mode==='schedule'?'Confirm schedule':'Confirm and post now'):confirmation.action==='cancel'?'Confirm cancellation':'Confirm retry'}</Button><Button variant="secondary" disabled={busy} onClick={()=>setConfirmation(null)}>Keep reviewing</Button></div></section>}
 </section><aside className="panel"><p className="eyebrow">PUBLICATION HISTORY</p><h2>Track your posts.</h2>{!rows.length&&<p>No publication requests yet.</p>}<ul className="video-version-list">{rows.map(r=><li key={r.id}><h3>{r.errorCode==='DELIVERY_WINDOW_EXPIRED'?'Delivery window expired':labels[r.state]}</h3><p>@{r.destination.usernameAtApproval} · Video {r.videoId.slice(-8)}</p><p className="publish-caption-text">{r.caption||'(No caption)'}</p><p>{new Date(r.createdAt).toLocaleString()}</p>{r.schedule&&<p>Scheduled: <strong>{r.schedule.localTime.replace('T',' ')} · {r.schedule.timezone} · UTC{r.schedule.utcOffset}</strong></p>}{r.state==='published'?(r.permalink?<a href={r.permalink} target="_blank" rel="noopener noreferrer">View Instagram Reel ↗</a>:<p>Instagram confirmed publication. The Reel link is unavailable; check the account directly.</p>):['outcome_unknown','needs_attention'].includes(r.state)?<p className="notice">Submission may have succeeded. We will not automatically submit again. Check the Instagram account before any further action.</p>:r.errorCode&&<p>{r.errorCode==='DELIVERY_WINDOW_EXPIRED'?'Delivery window expired. Nothing was submitted. Edit and confirm a new time.':r.state==='paused_auth'?'Reconnect the original account, refresh and review before retrying.':'No publication was submitted. Review the connection and media before retrying.'}</p>}{r.actions.edit&&<Button disabled={blocked||!!confirmation||!enabled} variant="secondary" onClick={()=>edit(r)}>Edit / reschedule</Button>}{r.actions.cancel&&<Button disabled={blocked||!!confirmation} variant="secondary" onClick={()=>{setConfirmationDetails({account:r.destination.usernameAtApproval,caption:r.caption,videoId:r.videoId,timing:r.schedule?`${r.schedule.localTime.replace('T',' ')} · ${r.schedule.timezone} · UTC${r.schedule.utcOffset}`:'Post now'});setConfirmation({key:crypto.randomUUID(),id:r.id,action:'cancel',body:{expectedRevision:r.revision,confirm:true}});}}>Cancel request</Button>}{r.actions.retry&&<Button disabled={blocked||!enabled||!!confirmation} onClick={()=>{setConfirmationDetails({account:r.destination.usernameAtApproval,caption:r.caption,videoId:r.videoId,timing:r.schedule?`${r.schedule.localTime.replace('T',' ')} · ${r.schedule.timezone} · UTC${r.schedule.utcOffset}`:'Post now'});setConfirmation({key:crypto.randomUUID(),id:r.id,action:'retry',body:{expectedRevision:r.revision,confirm:true}});}}>Review retry</Button>}</li>)}</ul>{cursor&&<Button disabled={busy} variant="secondary" onClick={()=>void load(true)}>Load older publications</Button>}</aside></div>}
 </main>;
}
