'use client';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {Button} from '../ui';
import {videoView,type Video} from '../../src/videos/contracts';
import {connectionView,type ConnectionView} from '../../src/instagram/contracts';
import {intentView,publishInput,type PublishIntent} from '../../src/publishing/contracts';
import {publicationStore,recoverPublication,type Receipt} from './commands';
import {signInLocation} from '../../src/auth/navigation';
const historySchema=z.object({data:z.array(intentView),page:z.object({nextCursor:z.string().nullable()}),enabled:z.boolean()});
const labels:Record<string,string>={queued:'Queued for Instagram',preparing:'Preparing the Reel',processing:'Instagram is processing your video',submitting:'Submitting to Instagram',published:'Published',paused_auth:'Review your connection',failed_safe:'Not published — safe to retry',outcome_unknown:'Publication outcome unconfirmed',needs_attention:'Publication needs manual review',cancelled:'Cancelled'};
export function PublishPanel({projectId,videoId,userId}:{projectId:string;videoId:string;userId:string}){
 const [video,setVideo]=useState<Video|null>(null),[connection,setConnection]=useState<ConnectionView|null>(null),[rows,setRows]=useState<PublishIntent[]>([]),[cursor,setCursor]=useState<string|null>(null),[enabled,setEnabled]=useState(false),[caption,setCaption]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Receipt|null>(null),[confirmation,setConfirmation]=useState<Receipt|null>(null),[preview,setPreview]=useState<string|null>(null),[confirmationDetails,setConfirmationDetails]=useState<{account:string;caption:string;videoId:string}|null>(null);
 const active=useRef(false),lock=useRef(false),storage=useRef<ReturnType<typeof publicationStore>|null>(null),draftKey=`namaste:post-caption:${userId}:${projectId}:${videoId}`;
 async function get(url:string,body?:unknown){const r=await fetch(url,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000),...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const b=await r.json();if(!r.ok)throw {code:b.error?.code,message:b.error?.message};return b;}
 function failure(e:unknown){const x=e as {code?:string;message?:string};if(x.code==='UNAUTHENTICATED')window.location.replace(signInLocation('expired'));else if(x.code==='ACCESS_DISABLED')window.location.replace('/access-help?state=disabled');setError(x.code==='PUBLICATION_EXISTS'?'This video already has a publication for this account. Review the history below.':x.code==='PUBLISHING_DISABLED'?'Publishing is awaiting administrator activation. Nothing was queued.':x.code==='REVISION_CONFLICT'?'Publication changed in another tab. Refresh and review its current state.':x.code==='DESTINATION_CHANGED'||x.code==='RECONNECT_REQUIRED'?'The destination changed or needs reconnecting. Refresh and review the account again.':x.code==='VIDEO_NOT_APPROVED'?'Approve this exact video in the video review screen.':x.message??'Could not confirm this request. Recover it below if pending; otherwise refresh.');}
 async function load(more=false){if(lock.current)return;lock.current=true;setBusy(true);try{const [v,c,h]=await Promise.all([get(`/api/videos/${videoId}`),get('/api/instagram/connection'),get(`/api/projects/${projectId}/publish-intents?limit=20${more&&cursor?`&cursor=${cursor}`:''}`)]);const selected=videoView.parse(v.data);if(selected.projectId!==projectId)throw {code:'NOT_FOUND',message:'Video does not belong to this project.'};const history=historySchema.parse(h);if(!active.current)return;setVideo(selected);setConnection(c.data?connectionView.parse(c.data):null);setRows(old=>more?[...new Map([...old,...history.data].map(x=>[x.id,x])).values()]:history.data);setCursor(history.page.nextCursor);setEnabled(history.enabled);setReady(true);}catch(e){if(active.current)failure(e);}finally{lock.current=false;if(active.current)setBusy(false);}}
 useEffect(()=>{active.current=true;try{storage.current=publicationStore(sessionStorage,userId,projectId);setPending(storage.current.read());setCaption(sessionStorage.getItem(draftKey)??'');}catch{setError('Browser recovery storage is unavailable. Enable it before publishing.');storage.current=null;}void load();return()=>{active.current=false;};},[projectId,videoId,userId]);
 useEffect(()=>{if(!rows.some(r=>['queued','preparing','processing','submitting','outcome_unknown'].includes(r.state)))return;const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},10000);return()=>clearInterval(timer);},[rows]);
 async function submit(command:Receipt,recover=false){if(lock.current||!storage.current)return;lock.current=true;setBusy(true);setError('');try{if(!recover){storage.current.write(command);setPending(command);}setConfirmation(null);const result=await recoverPublication(storage.current,command);if(active.current){setRows(old=>[result,...old.filter(r=>r.id!==result.id)]);setPending(null);}}catch(e){if(active.current){try{setPending(storage.current.read());}catch{storage.current=null;}failure(e);}}finally{lock.current=false;if(active.current)setBusy(false);}}
 function review(){if(!video?.approval||!connection?.account)return;const body=publishInput.parse({projectId,payload:{videoId:video.id,videoApprovalId:video.approval.id,expectedOutputHash:video.outputHash,destination:{connectionId:connection.id,instagramUserId:connection.account.id,destinationEpoch:connection.destinationEpoch},caption},mode:'now',confirm:true});setConfirmationDetails({account:connection.account.username,caption:body.payload.caption,videoId:video.id});setConfirmation({key:crypto.randomUUID(),action:'create',body});}
 const blocked=busy||!!pending||!storage.current,existing=rows.some(r=>r.videoId===videoId&&r.destination.instagramUserId===connection?.account?.id);
 return <main id="main" className="container foundation video-review" data-private-focus-scope><nav className="actions" aria-label="Project steps"><a href="/projects">← My videos</a><a href={`/projects/${projectId}/video`}>Video review</a><span aria-current="step">04 · Publish</span></nav><p className="eyebrow">READY FOR THE WORLD</p><h1>Your next Reel.</h1><p>Review the exact video, destination and caption before posting.</p>
 {error&&<p role="alert" className="notice notice--error">{error}</p>}
 {pending&&<section className="notice"><h2>Recover your request</h2><p>The {pending.action} response is unconfirmed. Recovery reuses the same command; it does not create a second post.</p><Button disabled={busy} onClick={()=>void submit(pending,true)}>Recover request</Button></section>}
 <Button variant="secondary" disabled={busy} onClick={()=>{setConfirmation(null);void load();}}>Refresh publication status</Button>
 {!ready?<p role="status">{busy?'Loading your publication details…':'Refresh to load your publication details.'}</p>:<div className="video-review-grid"><section className="panel"><p className="eyebrow">EXACT VIDEO</p><h2>{video?.title}</h2><p>Version {video?.id.slice(-8)} · {Math.round(video?.duration??0)} seconds</p>{!video?.approval?<p className="notice">This version needs approval. <a href={`/projects/${projectId}/video`}>Review and approve it</a> first.</p>:<p>Approved video version</p>}
 {preview&&<div className="video-review-player"><video aria-label="Publication video preview" controls playsInline src={preview} onError={()=>{setPreview(null);setError('Preview expired. Open it again; the saved video is unchanged.');}}/></div>}
 <Button variant="secondary" disabled={blocked||!video} onClick={async()=>{if(!video||lock.current)return;lock.current=true;setBusy(true);try{const b=await get(`/api/assets/${video.outputAssetId}/access`,{purpose:'preview'});if(active.current)setPreview(b.data.url);}catch(e){failure(e);}finally{lock.current=false;setBusy(false);}}}>Open video preview</Button>
 <h3>Instagram destination</h3>{connection?.account?<p><strong>@{connection.account.username}</strong> · {connection.state.replaceAll('_',' ')}</p>:<p>No Instagram account connected.</p>}<a href={`/settings/instagram?project=${projectId}`}>Manage Instagram connection</a>
 <label className="publish-caption">Post caption<textarea aria-label="Post caption" rows={6} value={caption} disabled={blocked||!!confirmation} onChange={e=>{try{sessionStorage.setItem(draftKey,e.target.value);setCaption(e.target.value);}catch{setError('Could not save your caption for recovery.');}}}/></label><p>{[...caption].length} / 2,200 characters · Saved in this tab</p>
 {!enabled&&<p className="notice">Posting is awaiting administrator activation. You can review your video and prepare a caption now.</p>}
 <Button disabled={blocked||!enabled||!video?.approval||!connection?.publishingAvailable||[...caption].length>2200||existing||!!confirmation} onClick={review}>Review post</Button>{existing&&<p>This version already has a publication for this account. Use its history below.</p>}
 {confirmation&&<section className="notice" aria-label="Confirm Instagram publication"><h3>{confirmation.action==='create'?'Post this Reel now?':confirmation.action==='cancel'?'Cancel before submission?':'Retry this exact post?'}</h3>{confirmation.action==='create'?<><p>Video {confirmationDetails?.videoId.slice(-8)} → <strong>@{confirmationDetails?.account}</strong></p><p className="publish-caption-text">{confirmation.body.payload.caption||'(No caption)'}</p><p>This sends the approved video and caption to Instagram and publishes a Reel to this account. It may appear in the feed. Publishing cannot be cancelled once submission starts.</p></>:<><p>Video {confirmationDetails?.videoId.slice(-8)} → <strong>@{confirmationDetails?.account}</strong></p><p className="publish-caption-text">{confirmationDetails?.caption||'(No caption)'}</p><p>{confirmation.action==='retry'?'Uses the original video, caption and original account. Refresh the connection first if required.':'An already submitted post cannot be cancelled here.'}</p></>}<div className="actions"><Button disabled={blocked} onClick={()=>void submit(confirmation)}>{confirmation.action==='create'?'Confirm and post now':confirmation.action==='cancel'?'Confirm cancellation':'Confirm retry'}</Button><Button variant="secondary" disabled={busy} onClick={()=>setConfirmation(null)}>Keep reviewing</Button></div></section>}
 </section><aside className="panel"><p className="eyebrow">PUBLICATION HISTORY</p><h2>Track your posts.</h2>{!rows.length&&<p>No publication requests yet.</p>}<ul className="video-version-list">{rows.map(r=><li key={r.id}><h3>{labels[r.state]}</h3><p>@{r.destination.usernameAtApproval} · Video {r.videoId.slice(-8)}</p><p className="publish-caption-text">{r.caption||'(No caption)'}</p><p>{new Date(r.createdAt).toLocaleString()}</p>{r.state==='published'?(r.permalink?<a href={r.permalink} target="_blank" rel="noopener noreferrer">View Instagram Reel ↗</a>:<p>Instagram confirmed publication. The Reel link is unavailable; check the account directly.</p>):['outcome_unknown','needs_attention'].includes(r.state)?<p className="notice">Submission may have succeeded. We will not automatically submit again. Check the Instagram account before any further action.</p>:r.errorCode&&<p>{r.state==='paused_auth'?'Reconnect the original account, refresh and review before retrying.':'No publication was submitted. Review the connection and media before retrying.'}</p>}{r.actions.cancel&&<Button disabled={blocked||!!confirmation} variant="secondary" onClick={()=>{setConfirmationDetails({account:r.destination.usernameAtApproval,caption:r.caption,videoId:r.videoId});setConfirmation({key:crypto.randomUUID(),id:r.id,action:'cancel',body:{expectedRevision:r.revision,confirm:true}});}}>Cancel request</Button>}{r.actions.retry&&<Button disabled={blocked||!enabled||!!confirmation} onClick={()=>{setConfirmationDetails({account:r.destination.usernameAtApproval,caption:r.caption,videoId:r.videoId});setConfirmation({key:crypto.randomUUID(),id:r.id,action:'retry',body:{expectedRevision:r.revision,confirm:true}});}}>Review retry</Button>}</li>)}</ul>{cursor&&<Button disabled={busy} variant="secondary" onClick={()=>void load(true)}>Load older publications</Button>}</aside></div>}
 </main>;
}
