'use client';
import {useEffect,useRef,useState} from 'react';
import {Brand,Button} from '../ui';
import {VoicePreview} from '../idea/voice-preview';
import {SignOutButton} from '../private-session';
import {signInLocation} from '../../src/auth/navigation';
import {validTimezone} from '../../src/preferences/contracts';
import {preferenceController,preferenceStore,preferenceTransport,type PreferenceState} from './controller';
const initial:PreferenceState={current:null,draft:null,pending:null,busy:false,ready:false,error:'',saved:false};
export function Settings({userId,name,email}:{userId:string;name:string;email:string}){
 const [confirmLeave,setConfirmLeave]=useState(false),[state,setState]=useState(initial),[zones,setZones]=useState<string[]>(['Asia/Kolkata','UTC']),controller=useRef<ReturnType<typeof preferenceController>|null>(null),leaving=useRef(false);
 useEffect(()=>{try{setZones([...new Set(['Asia/Kolkata','UTC',...Intl.supportedValuesOf('timeZone')])].sort());}catch{}
  let c:ReturnType<typeof preferenceController>;try{c=preferenceController(preferenceStore(sessionStorage,userId),preferenceTransport,s=>{setState(s);if(s.error==='UNAUTHENTICATED')window.location.replace(signInLocation('expired'));if(s.error==='ACCESS_DISABLED')window.location.replace('/access-help?state=disabled');});}catch{setState({...initial,error:'RECOVERY_STORAGE'});return;}
  controller.current=c;void c.load();return()=>c.dispose();
 },[userId]);
 const blocked=state.busy||!!state.pending||!state.ready,dirty=!!state.draft&&!!state.current&&(state.draft.timezone!==state.current.timezone||state.draft.defaultVoicePreset!==state.current.defaultVoicePreset);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(!leaving.current&&(dirty||state.pending)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,state.pending]);
 const message=state.error==='REVISION_CONFLICT'?'The saved preferences changed. Compare them below before saving your changes again.':state.error==='INVALID_TIMEZONE'?'Choose a valid IANA timezone.':state.error==='VOICE_UNAVAILABLE'?'That voice is unavailable. Choose Daniel for testing.':state.error==='RECOVERY_STORAGE'?'Browser recovery storage is unavailable. Enable storage and reload before saving.':state.error?'Could not confirm this request. Recover the pending save or reload preferences.':'';
 return <div className="library-shell"><aside className="library-sidebar"><Brand documentNavigation/><p className="workspace-label">PERSONAL WORKSPACE</p><nav aria-label="Workspace"><a href="/projects">My videos</a><a href="/settings" aria-current="page">Settings</a></nav></aside><div className="library-content"><header className="library-topbar"><a href="/projects">← My videos</a><div className="library-account"><span>{name}</span><SignOutButton beforeSignOut={()=>{if((dirty||state.pending)&&!confirmLeave){setConfirmLeave(true);return false;}leaving.current=true;return true;}} onSignOutFailed={()=>{leaving.current=false;setConfirmLeave(false);}}/></div></header><main id="main" className="preferences-main"><p className="eyebrow">MAKE IT YOURS</p><h1>Your workspace, your defaults.</h1><p className="muted">A few preferences for what you create next.</p>
 {confirmLeave&&<section className="notice" role="group" aria-label="Unsaved settings"><h2>Leave your settings?</h2><p>Unsaved edits will be discarded. An unresolved save stays recoverable in this tab. Choose Sign out again to confirm.</p><Button variant="secondary" onClick={()=>setConfirmLeave(false)}>Keep editing</Button></section>}
 {message&&<p role="alert">{message}</p>}{state.busy&&<p role="status">Updating preferences…</p>}{state.saved&&<p role="status">Preferences saved. Existing projects are unchanged.</p>}
 {state.pending&&!state.busy&&<section className="notice"><h2>Confirm your last save</h2><p>The result is unknown. Recover the original request before making another change.</p><Button disabled={state.busy} onClick={()=>void controller.current?.recover()}>Recover save</Button></section>}
 {!state.current&&<Button variant="secondary" disabled={state.busy} onClick={()=>void controller.current?.load()}>Reload preferences</Button>}
 {state.draft&&<form className="panel preferences-form" onSubmit={e=>{e.preventDefault();void controller.current?.save();}}><h2>Personal preferences</h2><p>Account: {email}</p><label>Timezone<input aria-invalid={!validTimezone(state.draft.timezone)} list="timezones" value={state.draft.timezone} disabled={blocked} maxLength={100} onChange={e=>controller.current?.edit('timezone',e.target.value)}/></label><datalist id="timezones">{zones.map(zone=><option key={zone} value={zone}/>)}</datalist>{!validTimezone(state.draft.timezone)&&<p role="alert">Enter a valid IANA timezone, for example Asia/Kolkata or UTC.</p>}<p className="muted">Use an IANA timezone, such as Asia/Kolkata. This will be your default when scheduling becomes available.</p><label>Voice for new projects<select value={state.draft.defaultVoicePreset} disabled={blocked} onChange={e=>controller.current?.edit('defaultVoicePreset',e.target.value)}>{state.draft.defaultVoicePreset!=='daniel-test'&&<option value={state.draft.defaultVoicePreset} disabled>Previously selected voice (unavailable)</option>}<option value="daniel-test">Daniel · testing voice</option></select></label><p className="muted">Daniel is the currently supported voice. This preference applies only when you create a new project; your existing narration and videos stay unchanged.</p>
 {state.error==='REVISION_CONFLICT'&&state.current&&<section className="notice"><h3>Currently saved</h3><p>Timezone: {state.current.timezone}<br/>Voice: {state.current.defaultVoicePreset}</p><Button variant="secondary" disabled={blocked} onClick={()=>controller.current?.useSaved()}>Use saved preferences</Button></section>}
 <VoicePreview preset={state.draft.defaultVoicePreset}/><div className="actions"><Button type="submit" disabled={blocked||!state.current||!dirty||!validTimezone(state.draft.timezone)||state.draft.defaultVoicePreset!=='daniel-test'}>{state.error==='REVISION_CONFLICT'?'Save my changes':'Save preferences'}</Button><Button variant="secondary" disabled={blocked} onClick={()=>controller.current?.useSaved()}>Discard changes</Button></div></form>}
 </main></div></div>;
}
